### ISSUE TITLE
API Routing refactor needed

### ISSUE THREAD

**Issue by dicedtomatoreal** [dicedtomatoreal/typex#10]
API routes need a good ol refactor as they are pretty messy.

**Comment by KryskZ09** [comment]
oo.refavtor?

**Comment by dicedtomatoreal** [comment]
> oo.refavtor?

Fixed!

**Comment by dicedtomatoreal** [comment]
# Routes
- /api/upload
- /api/shorten
- /api/users
  - POST (Create user with correct JSON payload)
  - GET (Returns array of User)
- /api/users/:id
  - PATCH (Edits a user, or with reset payload will reset password)
  - GET (Get a User)
  - DELETE (Delete a User)
- /api/images
  - GET
- /api/images?page=0
  - GET
- /api/images/:id
  - GET
  - DELETE
- /api/shortens
  - GET
- /api/shortens/:id
  - GET
  - DELETE

# Payloads 
- USER_CREATE
- USER_EDIT
- USER_RESET_PASSWORS
- USER_DELETE
- USER_DELETE_IMAGES
- IMAGE_DELETE
- SHORTEN_DELETE

**Comment by dicedtomatoreal** [comment]
Pages API will remain, and the above comment has been edited to fit.

**Comment by dicedtomatoreal** [comment]
new api routes have been implemented :D
