### ISSUE TITLE
NPM Build gives me this error

### ISSUE THREAD

**Issue by RehanPlayz** [dicedtomatoreal/typex#102]
(Without Docker and using NPM instead of Yarn)
https://paste.gg/p/anonymous/600a281c3d7c4595b1288deae4c6baef

@diced

**Comment by AlphaNecron** [comment]
Why Windows...

**Comment by RehanPlayz** [comment]
> Why Windows...

I'm just testing it on my PC not actually going to use it in production

**Comment by diced** [comment]
you will have to run `npm run build:schema` and `npm run build:next` manually since npm-run-all doesn't work on windows. after this you should be able to do `npm start`

**Comment by RehanPlayz** [comment]
> you will have to run `npm run build:schema` and `npm run build:next` manually since npm-run-all doesn't work on windows. after this you should be able to do `npm start`

Oh ok thx

**Comment by RehanPlayz** [comment]
> > you will have to run `npm run build:schema` and `npm run build:next` manually since npm-run-all doesn't work on windows. after this you should be able to do `npm start`
> 
> Oh ok thx

Also I'm using the latest NodeJS LTS Version if that matters

**Comment by AlphaNecron** [comment]
Use NodeJS 16.

**Comment by RehanPlayz** [comment]
> Use NodeJS 16.

Oh ok thx

**Comment by diced** [comment]
we support node 14+ but recommend 16. It's ultimately your choice

**Comment by AlphaNecron** [comment]
> we support node 14+ but recommend 16. It's ultimately your choice

`base64url` requires `node` >= 15.

**Comment by RehanPlayz** [comment]
> > we support node 14+ but recommend 16. It's ultimately your choice
> 
> `base64url` requires `node` >= 15.

I will just use node 16 then

**Comment by RehanPlayz** [comment]
"urls.route is a required field"

**Comment by AlphaNecron** [comment]
> "urls.route is a required field"

Set `urls.route` in your `config.toml`.

**Comment by RehanPlayz** [comment]
> > "urls.route is a required field"
> 
> Set `urls.route` in your `config.toml`.

I already set it as the default

**Comment by RehanPlayz** [comment]
route = '/u'

**Comment by AlphaNecron** [comment]
```toml
[urls]
route = '/go'
length = 6
```
Add it to the bottom of your `config.toml`

**Comment by RehanPlayz** [comment]
> ```toml
> [urls]
> route = '/go'
> length = 6
> ```
> 
> Add it to the bottom of your `config.toml`

thx

**Comment by RehanPlayz** [comment]
> ```toml
> [urls]
> route = '/go'
> length = 6
> ```
> 
> Add it to the bottom of your `config.toml`

https://paste.gg/p/anonymous/e220591e6fce46e6b850620a166eca86

**Comment by RehanPlayz** [comment]
https://paste.gg/p/anonymous/501c98478d114ffdb76c9a96d750a0e0

**Comment by AlphaNecron** [comment]
Use Linux then, most of the codes are not compatible with Windows.

**Comment by RehanPlayz** [comment]
> Use Linux then, most of the codes are not compatible with Windows.

Soooo I cant test it out on my PC?, I wasn't going to actually use Zipline but just test it

**Comment by AlphaNecron** [comment]
> > Use Linux then, most of the codes are not compatible with Windows.
> 
> Soooo I cant test it out on my PC?, I wasn't going to actually use Zipline but just test it

Use Docker.

**Comment by RehanPlayz** [comment]
> > > Use Linux then, most of the codes are not compatible with Windows.
> > 
> > 
> > Soooo I cant test it out on my PC?, I wasn't going to actually use Zipline but just test it
> 
> Use Docker.

ok
