### ISSUE TITLE
Ratelimiting

### ISSUE THREAD

**Issue by rpxs** [dicedtomatoreal/typex#110]
Feature request: add ratelimiting for the image upload endpoint.

ex: users can upload x images every x minutes or something. Configuration options available for it would also be just dandy.

**Comment by AlphaNecron** [comment]
I think @diced will migrate to Next 12 and rewrite the middleware, then there will be ratelimiting.

**Comment by diced** [comment]
it'll be added to 3.3 don't get your hopes up that it'll be next 12 though

**Comment by rpxs** [comment]
allah
