### ISSUE TITLE
url not found

### ISSUE THREAD

**Issue by rolkoztm** [dicedtomatoreal/typex#123]
![image](https://user-images.githubusercontent.com/60612933/153421839-1563c4d4-9574-4b33-baf6-a3a3f3930d65.png)
hey im getting error url is empty 😭 but the file actually uploading to the host

**Comment by diced** [comment]
Could you send the sharex custom uploader screen (hide any sensitive details)?

**Comment by InfiniteCod3** [comment]
Same happens to me

**Comment by InfiniteCod3** [comment]
![image](https://user-images.githubusercontent.com/91837651/153959249-e352b7d9-233f-48fc-a2dd-3636247a6569.png)

**Comment by InfiniteCod3** [comment]
this is how my custom uploader screen looks like and im getting the same error as the person who made the issue.

**Comment by diced** [comment]
In the JSON section (Parse Response} you should see $json:url$, change this to $json:files[0]$

Sorry about this, the ShareX file generator wasn't changed to reflect this changed property, I'll be pushing it very soon.

**Comment by InfiniteCod3** [comment]
Thanks very much, that fixed my problem.

**Comment by diced** [comment]
No problem, thanks for the insight.
