### ISSUE TITLE
sharex custom domain

### ISSUE THREAD

**Issue by ahatdude** [dicedtomatoreal/typex#128]
Hi,

I'm having an issue getting sharex to work with my custom domain. It works fine locally, but when I run it through my custom domain I get the following error on sharex when pressing the "test" button:

```
Error:
Error message:
The request was aborted: Could not create SSL/TLS secure channel.

Request URL:
https://sharex.MYDOMAIN.COM/api/upload

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

My setup is as follows:
My operating system is unRAID.
I'm running zipline as a docker. It's currently using "nginx proxy manager" also as a docker with a cloudflare certificate attached to it. I can access zipline through the cname I set on cloudflare - sharex.MYDOMAIN.COM

However, when testing it on sharex program on my windows computer after importing the "zipline.sxcu" it doesn't seem to work and gives me the error mentioned above.

I'd be glad to give you any more information you may need.

Thanks!

**Comment by diced** [comment]
Is MYDOMAIN.COM just for redaction purposes? Other than that i'm not sure why this is happening, you need to provide logs from Zipline, and double check that you are serving the correct port on nginx, zipline, and on cloudflare make sure its the correct IP. There is also a possibility that the certificate is invalid, thus using https wouldn't work. You can try to use the http version and see if it works.

**Comment by ahatdude** [comment]
Thanks for your response.

Yes, MYDOMAIN.COM is for redaction purposes.

I tried looking for logs to help, but I don't see them being created and saved to anywhere. Is there a variable I can add that will create a logs directory?

The only logs I can see are given to me by the container itself in unraid. Here they are:
```
yesterday at 19:24:522022-03-01 07:24:52,559 PM INFO  [server] starting zipline@3.4.0 server
yesterday at 19:24:522022-03-01 07:24:52,565 PM INFO  [config] reading environment
yesterday at 19:24:532022-03-01 07:24:53,074 PM INFO  [server] listening on 0.0.0.0:3000
yesterday at 19:25:272022-03-01 07:25:27,159 PM INFO  [url] /dashboard
yesterday at 19:25:272022-03-01 07:25:27,314 PM INFO  [url] /api/user
yesterday at 19:25:272022-03-01 07:25:27,369 PM INFO  [config] reading environment
yesterday at 19:25:272022-03-01 07:25:27,505 PM INFO  [url] /api/user/files
yesterday at 19:25:272022-03-01 07:25:27,589 PM INFO  [url] /api/user/recent?filter=media
yesterday at 19:25:272022-03-01 07:25:27,631 PM INFO  [url] /api/stats
yesterday at 19:25:382022-03-01 07:25:38,021 PM INFO  [url] /dashboard
yesterday at 19:25:382022-03-01 07:25:38,196 PM INFO  [url] /api/user
yesterday at 19:25:382022-03-01 07:25:38,303 PM INFO  [url] /api/user/files
yesterday at 19:25:382022-03-01 07:25:38,361 PM INFO  [url] /api/user/recent?filter=media
yesterday at 19:25:382022-03-01 07:25:38,405 PM INFO  [url] /api/stats
yesterday at 19:25:442022-03-01 07:25:44,776 PM INFO  [url] /dashboard
yesterday at 19:25:442022-03-01 07:25:44,987 PM INFO  [url] /api/user
yesterday at 19:25:452022-03-01 07:25:45,010 PM INFO  [url] /favicon.ico
yesterday at 19:25:452022-03-01 07:25:45,100 PM INFO  [url] /api/user/files
yesterday at 19:25:452022-03-01 07:25:45,154 PM INFO  [url] /api/user/recent?filter=media
yesterday at 19:25:452022-03-01 07:25:45,200 PM INFO  [url] /api/stats
yesterday at 19:29:472022-03-01 07:29:47,345 PM INFO  [url] /dashboard
yesterday at 19:29:472022-03-01 07:29:47,503 PM INFO  [url] /api/user
yesterday at 19:29:472022-03-01 07:29:47,605 PM INFO  [url] /api/user/files
yesterday at 19:29:472022-03-01 07:29:47,671 PM INFO  [url] /api/user/recent?filter=media
yesterday at 19:29:472022-03-01 07:29:47,717 PM INFO  [url] /api/stats
yesterday at 19:54:532022-03-01 07:54:53,262 PM INFO  [server] stats updated
yesterday at 20:24:532022-03-01 08:24:53,361 PM INFO  [server] stats updated
yesterday at 20:54:532022-03-01 08:54:53,462 PM INFO  [server] stats updated
yesterday at 21:24:532022-03-01 09:24:53,562 PM INFO  [server] stats updated
yesterday at 21:54:532022-03-01 09:54:53,662 PM INFO  [server] stats updated
yesterday at 22:24:532022-03-01 10:24:53,762 PM INFO  [server] stats updated
yesterday at 22:54:532022-03-01 10:54:53,862 PM INFO  [server] stats updated
yesterday at 23:24:532022-03-01 11:24:53,957 PM INFO  [server] stats updated
yesterday at 23:54:542022-03-01 11:54:54,037 PM INFO  [server] stats updated
today at 00:24:542022-03-02 12:24:54,137 AM INFO  [server] stats updated
today at 00:54:542022-03-02 12:54:54,151 AM INFO  [server] stats updated
today at 01:24:542022-03-02 01:24:54,150 AM INFO  [server] stats updated
today at 01:54:542022-03-02 01:54:54,223 AM INFO  [server] stats updated
today at 02:24:542022-03-02 02:24:54,310 AM INFO  [server] stats updated
today at 02:54:542022-03-02 02:54:54,395 AM INFO  [server] stats updated
today at 03:24:542022-03-02 03:24:54,494 AM INFO  [server] stats updated
today at 03:39:232022-03-02 03:39:23,212 AM INFO  [url] /api/user
today at 03:39:232022-03-02 03:39:23,384 AM INFO  [url] /api/user/files
today at 03:39:232022-03-02 03:39:23,583 AM INFO  [url] /api/user/recent?filter=media
today at 03:39:232022-03-02 03:39:23,642 AM INFO  [url] /api/stats
today at 03:54:542022-03-02 03:54:54,594 AM INFO  [server] stats updated
today at 04:24:542022-03-02 04:24:54,695 AM INFO  [server] stats updated
today at 04:54:542022-03-02 04:54:54,794 AM INFO  [server] stats updated
today at 05:24:542022-03-02 05:24:54,915 AM INFO  [server] stats updated
today at 05:54:542022-03-02 05:54:54,997 AM INFO  [server] stats updated
today at 06:24:552022-03-02 06:24:55,094 AM INFO  [server] stats updated
today at 06:54:552022-03-02 06:54:55,194 AM INFO  [server] stats updated
today at 07:24:552022-03-02 07:24:55,261 AM INFO  [server] stats updated
today at 07:54:552022-03-02 07:54:55,359 AM INFO  [server] stats updated
today at 08:24:552022-03-02 08:24:55,433 AM INFO  [server] stats updated
today at 08:54:552022-03-02 08:54:55,536 AM INFO  [server] stats updated
today at 09:24:552022-03-02 09:24:55,632 AM INFO  [server] stats updated
today at 09:54:552022-03-02 09:54:55,732 AM INFO  [server] stats updated
today at 10:24:552022-03-02 10:24:55,833 AM INFO  [server] stats updated
today at 10:54:552022-03-02 10:54:55,932 AM INFO  [server] stats updated
today at 11:24:562022-03-02 11:24:56,032 AM INFO  [server] stats updated
today at 11:54:562022-03-02 11:54:56,132 AM INFO  [server] stats updated
today at 12:24:562022-03-02 12:24:56,178 PM INFO  [server] stats updated
today at 12:54:562022-03-02 12:54:56,278 PM INFO  [server] stats updated
today at 13:24:562022-03-02 01:24:56,351 PM INFO  [server] stats updated
today at 13:54:562022-03-02 01:54:56,451 PM INFO  [server] stats updated
today at 14:24:562022-03-02 02:24:56,558 PM INFO  [server] stats updated
today at 14:54:562022-03-02 02:54:56,655 PM INFO  [server] stats updated
today at 15:24:562022-03-02 03:24:56,746 PM INFO  [server] stats updated
today at 15:54:562022-03-02 03:54:56,837 PM INFO  [server] stats updated
today at 16:24:562022-03-02 04:24:56,919 PM INFO  [server] stats updated
today at 16:29:432022-03-02 04:29:43,376 PM INFO  [url] /dashboard
today at 16:29:432022-03-02 04:29:43,510 PM INFO  [url] /api/user
today at 16:29:432022-03-02 04:29:43,594 PM INFO  [url] /api/user/files
today at 16:29:432022-03-02 04:29:43,619 PM INFO  [url] /favicon.ico
today at 16:29:432022-03-02 04:29:43,629 PM INFO  [url] /api/user/recent?filter=media
today at 16:29:432022-03-02 04:29:43,638 PM INFO  [url] /api/stats
today at 16:38:252022-03-02 04:38:25,411 PM INFO  [url] /dashboard
today at 16:38:252022-03-02 04:38:25,594 PM INFO  [url] /api/user
today at 16:38:252022-03-02 04:38:25,708 PM INFO  [url] /api/user/files
today at 16:38:252022-03-02 04:38:25,799 PM INFO  [url] /api/user/recent?filter=media
today at 16:38:252022-03-02 04:38:25,839 PM INFO  [url] /api/stats
today at 16:54:572022-03-02 04:54:57,019 PM INFO  [server] stats updated
today at 16:58:392022-03-02 04:58:39,755 PM INFO  [url] /dashboard
today at 16:58:392022-03-02 04:58:39,896 PM INFO  [url] /api/user
today at 16:58:402022-03-02 04:58:40,004 PM INFO  [url] /api/user/files
today at 16:58:402022-03-02 04:58:40,076 PM INFO  [url] /api/user/recent?filter=media
today at 16:58:402022-03-02 04:58:40,125 PM INFO  [url] /api/stats
today at 16:58:452022-03-02 04:58:45,265 PM INFO  [url] /api/user/urls
today at 17:09:412022-03-02 05:09:41,918 PM INFO  [url] /api/upload
today at 17:24:572022-03-02 05:24:57,056 PM INFO  [server] stats updated
today at 17:54:572022-03-02 05:54:57,086 PM INFO  [server] stats updated
today at 18:24:572022-03-02 06:24:57,185 PM INFO  [server] stats updated
today at 18:54:572022-03-02 06:54:57,286 PM INFO  [server] stats updated
today at 19:24:572022-03-02 07:24:57,337 PM INFO  [server] stats updated
today at 19:54:572022-03-02 07:54:57,400 PM INFO  [server] stats updated
today at 20:24:572022-03-02 08:24:57,456 PM INFO  [server] stats updated
today at 20:54:572022-03-02 08:54:57,552 PM INFO  [server] stats updated
```

When it comes to all the nginx and cloudflare variables, I know they are correct since all my containers are going through it using the same certificates and everything is fine. I'm even not passing through authelia, since I'm only testing for now.

Thanks.

**Comment by diced** [comment]
> Thanks for your response.
> 
> Yes, MYDOMAIN.COM is for redaction purposes.
> 
> I tried looking for logs to help, but I don't see them being created and saved to anywhere. Is there a variable I can add that will create a logs directory?
> 
> The only logs I can see are given to me by the container itself in unraid. Here they are:
> ```
> yesterday at 19:24:522022-03-01 07:24:52,559 PM INFO  [server] starting zipline@3.4.0 server
> yesterday at 19:24:522022-03-01 07:24:52,565 PM INFO  [config] reading environment
> yesterday at 19:24:532022-03-01 07:24:53,074 PM INFO  [server] listening on 0.0.0.0:3000
> yesterday at 19:25:272022-03-01 07:25:27,159 PM INFO  [url] /dashboard
> yesterday at 19:25:272022-03-01 07:25:27,314 PM INFO  [url] /api/user
> yesterday at 19:25:272022-03-01 07:25:27,369 PM INFO  [config] reading environment
> yesterday at 19:25:272022-03-01 07:25:27,505 PM INFO  [url] /api/user/files
> yesterday at 19:25:272022-03-01 07:25:27,589 PM INFO  [url] /api/user/recent?filter=media
> yesterday at 19:25:272022-03-01 07:25:27,631 PM INFO  [url] /api/stats
> yesterday at 19:25:382022-03-01 07:25:38,021 PM INFO  [url] /dashboard
> yesterday at 19:25:382022-03-01 07:25:38,196 PM INFO  [url] /api/user
> yesterday at 19:25:382022-03-01 07:25:38,303 PM INFO  [url] /api/user/files
> yesterday at 19:25:382022-03-01 07:25:38,361 PM INFO  [url] /api/user/recent?filter=media
> yesterday at 19:25:382022-03-01 07:25:38,405 PM INFO  [url] /api/stats
> yesterday at 19:25:442022-03-01 07:25:44,776 PM INFO  [url] /dashboard
> yesterday at 19:25:442022-03-01 07:25:44,987 PM INFO  [url] /api/user
> yesterday at 19:25:452022-03-01 07:25:45,010 PM INFO  [url] /favicon.ico
> yesterday at 19:25:452022-03-01 07:25:45,100 PM INFO  [url] /api/user/files
> yesterday at 19:25:452022-03-01 07:25:45,154 PM INFO  [url] /api/user/recent?filter=media
> yesterday at 19:25:452022-03-01 07:25:45,200 PM INFO  [url] /api/stats
> yesterday at 19:29:472022-03-01 07:29:47,345 PM INFO  [url] /dashboard
> yesterday at 19:29:472022-03-01 07:29:47,503 PM INFO  [url] /api/user
> yesterday at 19:29:472022-03-01 07:29:47,605 PM INFO  [url] /api/user/files
> yesterday at 19:29:472022-03-01 07:29:47,671 PM INFO  [url] /api/user/recent?filter=media
> yesterday at 19:29:472022-03-01 07:29:47,717 PM INFO  [url] /api/stats
> yesterday at 19:54:532022-03-01 07:54:53,262 PM INFO  [server] stats updated
> yesterday at 20:24:532022-03-01 08:24:53,361 PM INFO  [server] stats updated
> yesterday at 20:54:532022-03-01 08:54:53,462 PM INFO  [server] stats updated
> yesterday at 21:24:532022-03-01 09:24:53,562 PM INFO  [server] stats updated
> yesterday at 21:54:532022-03-01 09:54:53,662 PM INFO  [server] stats updated
> yesterday at 22:24:532022-03-01 10:24:53,762 PM INFO  [server] stats updated
> yesterday at 22:54:532022-03-01 10:54:53,862 PM INFO  [server] stats updated
> yesterday at 23:24:532022-03-01 11:24:53,957 PM INFO  [server] stats updated
> yesterday at 23:54:542022-03-01 11:54:54,037 PM INFO  [server] stats updated
> today at 00:24:542022-03-02 12:24:54,137 AM INFO  [server] stats updated
> today at 00:54:542022-03-02 12:54:54,151 AM INFO  [server] stats updated
> today at 01:24:542022-03-02 01:24:54,150 AM INFO  [server] stats updated
> today at 01:54:542022-03-02 01:54:54,223 AM INFO  [server] stats updated
> today at 02:24:542022-03-02 02:24:54,310 AM INFO  [server] stats updated
> today at 02:54:542022-03-02 02:54:54,395 AM INFO  [server] stats updated
> today at 03:24:542022-03-02 03:24:54,494 AM INFO  [server] stats updated
> today at 03:39:232022-03-02 03:39:23,212 AM INFO  [url] /api/user
> today at 03:39:232022-03-02 03:39:23,384 AM INFO  [url] /api/user/files
> today at 03:39:232022-03-02 03:39:23,583 AM INFO  [url] /api/user/recent?filter=media
> today at 03:39:232022-03-02 03:39:23,642 AM INFO  [url] /api/stats
> today at 03:54:542022-03-02 03:54:54,594 AM INFO  [server] stats updated
> today at 04:24:542022-03-02 04:24:54,695 AM INFO  [server] stats updated
> today at 04:54:542022-03-02 04:54:54,794 AM INFO  [server] stats updated
> today at 05:24:542022-03-02 05:24:54,915 AM INFO  [server] stats updated
> today at 05:54:542022-03-02 05:54:54,997 AM INFO  [server] stats updated
> today at 06:24:552022-03-02 06:24:55,094 AM INFO  [server] stats updated
> today at 06:54:552022-03-02 06:54:55,194 AM INFO  [server] stats updated
> today at 07:24:552022-03-02 07:24:55,261 AM INFO  [server] stats updated
> today at 07:54:552022-03-02 07:54:55,359 AM INFO  [server] stats updated
> today at 08:24:552022-03-02 08:24:55,433 AM INFO  [server] stats updated
> today at 08:54:552022-03-02 08:54:55,536 AM INFO  [server] stats updated
> today at 09:24:552022-03-02 09:24:55,632 AM INFO  [server] stats updated
> today at 09:54:552022-03-02 09:54:55,732 AM INFO  [server] stats updated
> today at 10:24:552022-03-02 10:24:55,833 AM INFO  [server] stats updated
> today at 10:54:552022-03-02 10:54:55,932 AM INFO  [server] stats updated
> today at 11:24:562022-03-02 11:24:56,032 AM INFO  [server] stats updated
> today at 11:54:562022-03-02 11:54:56,132 AM INFO  [server] stats updated
> today at 12:24:562022-03-02 12:24:56,178 PM INFO  [server] stats updated
> today at 12:54:562022-03-02 12:54:56,278 PM INFO  [server] stats updated
> today at 13:24:562022-03-02 01:24:56,351 PM INFO  [server] stats updated
> today at 13:54:562022-03-02 01:54:56,451 PM INFO  [server] stats updated
> today at 14:24:562022-03-02 02:24:56,558 PM INFO  [server] stats updated
> today at 14:54:562022-03-02 02:54:56,655 PM INFO  [server] stats updated
> today at 15:24:562022-03-02 03:24:56,746 PM INFO  [server] stats updated
> today at 15:54:562022-03-02 03:54:56,837 PM INFO  [server] stats updated
> today at 16:24:562022-03-02 04:24:56,919 PM INFO  [server] stats updated
> today at 16:29:432022-03-02 04:29:43,376 PM INFO  [url] /dashboard
> today at 16:29:432022-03-02 04:29:43,510 PM INFO  [url] /api/user
> today at 16:29:432022-03-02 04:29:43,594 PM INFO  [url] /api/user/files
> today at 16:29:432022-03-02 04:29:43,619 PM INFO  [url] /favicon.ico
> today at 16:29:432022-03-02 04:29:43,629 PM INFO  [url] /api/user/recent?filter=media
> today at 16:29:432022-03-02 04:29:43,638 PM INFO  [url] /api/stats
> today at 16:38:252022-03-02 04:38:25,411 PM INFO  [url] /dashboard
> today at 16:38:252022-03-02 04:38:25,594 PM INFO  [url] /api/user
> today at 16:38:252022-03-02 04:38:25,708 PM INFO  [url] /api/user/files
> today at 16:38:252022-03-02 04:38:25,799 PM INFO  [url] /api/user/recent?filter=media
> today at 16:38:252022-03-02 04:38:25,839 PM INFO  [url] /api/stats
> today at 16:54:572022-03-02 04:54:57,019 PM INFO  [server] stats updated
> today at 16:58:392022-03-02 04:58:39,755 PM INFO  [url] /dashboard
> today at 16:58:392022-03-02 04:58:39,896 PM INFO  [url] /api/user
> today at 16:58:402022-03-02 04:58:40,004 PM INFO  [url] /api/user/files
> today at 16:58:402022-03-02 04:58:40,076 PM INFO  [url] /api/user/recent?filter=media
> today at 16:58:402022-03-02 04:58:40,125 PM INFO  [url] /api/stats
> today at 16:58:452022-03-02 04:58:45,265 PM INFO  [url] /api/user/urls
> today at 17:09:412022-03-02 05:09:41,918 PM INFO  [url] /api/upload
> today at 17:24:572022-03-02 05:24:57,056 PM INFO  [server] stats updated
> today at 17:54:572022-03-02 05:54:57,086 PM INFO  [server] stats updated
> today at 18:24:572022-03-02 06:24:57,185 PM INFO  [server] stats updated
> today at 18:54:572022-03-02 06:54:57,286 PM INFO  [server] stats updated
> today at 19:24:572022-03-02 07:24:57,337 PM INFO  [server] stats updated
> today at 19:54:572022-03-02 07:54:57,400 PM INFO  [server] stats updated
> today at 20:24:572022-03-02 08:24:57,456 PM INFO  [server] stats updated
> today at 20:54:572022-03-02 08:54:57,552 PM INFO  [server] stats updated
> ```
> 
> When it comes to all the nginx and cloudflare variables, I know they are correct since all my containers are going through it using the same certificates and everything is fine. I'm even not passing through authelia, since I'm only testing for now.
> 
> Thanks.

Thanks for the extra info! Unfortunately I'm not able to figure out what the problem is, since it seems that zipline is working fine. Are you sure port 3000 is being exposed out of docker. Other than this (and you said you have checked your configs and ports) I'm not sure what to do. You can try doing this in a non unRAID system.

**Comment by ahatdude** [comment]
I will maybe spin up an ubuntu vm or something, but before that I'd like to confirm something:

You mentioned port 3000 being exposed out of docker, I have port 3000 directed to port 8095 (TCP) and since it's going through a reverse proxy, there should be no need to open the ports, right? I haven't had to do it for any other app. That should be fine, right?

What's confusing is that everything is fine locally but the moment I introduce the reverse proxy aspect, the TLS error comes in.

Are there any environmental variables that could help? Or are they all in the unRAID image you made? (I assume you made it)

Sorry about this and thanks for your time!

**Comment by diced** [comment]
Ah I totally forgot that you were running NGINX! Could you send over the config you are using?

**Comment by ahatdude** [comment]
I got this from your website and changed a few things:

```
server {
  listen 80 default_server;
  client_max_body_size 100M;
  server_name MYDOMAIN.COM;
  location / {
    proxy_pass http://localhost:8095;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
```

I added my domain and changed the port to what you see (it's the port that I have set for the container, as previously mentioned). I just added this in the "advanced" tab of nginx proxy manager.

**Comment by diced** [comment]
> I got this from your website and changed a few things:
> 
> ```
> server {
>   listen 80 default_server;
>   client_max_body_size 100M;
>   server_name MYDOMAIN.COM;
>   location / {
>     proxy_pass http://localhost:8095;
>     proxy_set_header Host $host;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header X-Forwarded-Proto $scheme;
>   }
> }
> ```
> 
> I added my domain and changed the port to what you see (it's the port that I have set for the container, as previously mentioned). I just added this in the "advanced" tab of nginx proxy manager.

I see, is "nginx proxy manager" a part of un raid that lets you interface with nginx? If so there's a possibility that it modifies the config and adds properties for ssl.

**Comment by ahatdude** [comment]
This is nginx proxy manager: https://nginxproxymanager.com/guide/

Essentially it makes my life easy when it comes to reverse proxying a service.

Here are a few screenshots of the settings I can change. The only thing I redacted are the ones that contain MYDOMAIN.COM

![EP0vMGXVWC](https://user-images.githubusercontent.com/97416616/156591623-d9a0d121-ad60-4081-9488-6a92878dbb35.png)

This is where I route my internal IP to the actual external URL name that I set up as a CNAME on cloudflare.

![opera_xQM62gd8XD](https://user-images.githubusercontent.com/97416616/156591666-5228e090-e0a3-4306-9469-9a1fd2fc1ac0.png)

I've never used this section, but I believe it for when you want your link to look like: www.MYDOMAIN.COM/sharex

![K4KNDpsYot](https://user-images.githubusercontent.com/97416616/156591710-10ecfd89-8a60-42f0-bf3e-073087620afb.png)

This is where I uploaded my cloudflare certification (10 years) and simply use it with everything I self host.

![XZE9xpdcq9](https://user-images.githubusercontent.com/97416616/156591751-41fe4801-5ecb-4c73-ab02-ca71cba621d7.png)

And this is where I added your nginx config. However, the moment I add it it stops working. If I remove the text, it works again (access to the webUI).

Thanks for your time :-)

**Comment by diced** [comment]
What do your Cloudflare SSL settings look like? And since you have SSL in that try turning off Cloudflare proxy (clicking orange cloud in DNS settings) and see if it still uses https. I usually just use the Cloudflare flexible SSL thing which is pretty easy since you don't need to add any SSL properties to your nginx or web server.

**Comment by ahatdude** [comment]
This is what my cloudflare SSL settings look like:

![opera_u7rJbxaCj8](https://user-images.githubusercontent.com/97416616/156608728-63e2c11f-bf00-4363-afaa-4dd2639d8f63.png)

I switched it to flexible and removed the Cloudflare proxy like you suggested and neither the WebUI or the api connection are working now.

I get this error from ShareX:
```
Error:
Error message:
Unable to connect to the remote server

Request URL:
https://sharex.serverthings.xyz/api/upload

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```
I just switched it back to "strict" and put the proxy on and I have access to the WebUI again. Confusing...

Thanks for helping.

**Comment by diced** [comment]
That's weird. Glad it works now! Have fun!

**Comment by ahatdude** [comment]
Oh sorry, I must have not explained myself correctly! The zipline server is still not accessible via sharex... changing the proxy settings in cloudflare basically made it completely inaccessible (WebUI and api), but having the settings on strict and proxied allows me to have access to the webui but NOT the api.

**Comment by diced** [comment]
> Oh sorry, I must have not explained myself correctly! The zipline server is still not accessible via sharex... changing the proxy settings in cloudflare basically made it completely inaccessible (WebUI and api), but having the settings on strict and proxied allows me to have access to the webui but NOT the api.

That's weird since the webui and api run on the same server?

**Comment by ahatdude** [comment]
Yup, the WebUI has been always functional... but when I try to get it working with sharex I get the first error I mentioned.

**Comment by ahatdude** [comment]
To follow up on this, I figured out the issue!

I changed my TLS minimum version on cloudflare to 1.2 and it worked.

![firefox_VmDH6oSMP6](https://user-images.githubusercontent.com/97416616/161388950-693231bc-788c-4295-a386-d3550b3028f3.png)


I would like to keep it at 1.3, is there something that can be done about this?
