### ISSUE TITLE
Cant upload.

### ISSUE THREAD

**Issue by boofiboi** [dicedtomatoreal/typex#134]
When uploading any file as any user, zipline outputs this in docker logs
[Error: EACCES: permission denied, open '/zipline/uploads/cIiv14.png'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/zipline/uploads/cIiv14.png'
}

The path /zipline/uploads has 777 permissions and is chowned by root.

I have no idea why its doing this and why it cant write (docker runs as root, and 777 makes everyone be able to write/read".

Any help?

**Comment by boofiboi** [comment]
Fixed, it actually wasnt 777.

**Comment by Kadantte** [comment]
Hw you changed the permission to 777 I wasn't able to do so! I git this error `chmod: Uploads: Operation not permitted`

**Comment by boofiboi** [comment]
> Hw you changed the permission to 777 I wasn't able to do so! I git this error `chmod: Uploads: Operation not permitted`

Run the command as root, or use any SFTP client and change them in there

**Comment by Kadantte** [comment]
> > Hw you changed the permission to 777 I wasn't able to do so! I git this error `chmod: Uploads: Operation not permitted`
> 
> Run the command as root, or use any SFTP client and change them in there
EDIT: Fixed I had to use root on docker bash

```shell
@Usui ➜ zipline git(trunk) # docker exec -u 0 -it zipline-zipline-1 /bin/sh
/zipline # chmod 777 uploads
```
root [ id = 0 ]

![image](https://user-images.githubusercontent.com/11579313/159722982-0045f5ee-ebc3-426c-b5a7-824da39ba5d2.png)


~I did I run it as an ADM but I get the same error I'm using the Docker version I might try it on WSL!~
