### ISSUE TITLE
Export data

### ISSUE THREAD

**Issue by Kadantte** [dicedtomatoreal/typex#137]
It would be great if the users can export their Data!

**Comment by diced** [comment]
This does seem like a great idea, maybe to add along with when users get deleted their entire images and stuff get deleted too, maybe as a "user overhaul" type thing. Just wondering what data we should export, because there is a lot of data about users and if I were to make something like this, I don't want to just take the raw stuff from the db and export it to a json or something.

**Comment by Kadantte** [comment]
> This does seem like a great idea, maybe to add along with when users get deleted their entire images and stuff get deleted too, maybe as a "user overhaul" type thing. Just wondering what data we should export, because there is a lot of data about users and if I were to make something like this, I don't want to just take the raw stuff from the db and export it to a json or something.

I don't mean personnel data like the username or email what I mean with data is the user uploaded pictures videos, and files, if a user wants to delete his account sometimes he wants to export his files first then do so!

**Comment by diced** [comment]
Ah I see, maybe some sort of zip file with their files?

**Comment by Kadantte** [comment]
> Ah I see, maybe some sort of zip file with their files?

Yeah, this is the idea! overall zipline is the best ShareX/File upload server that [hosted](https://s1.why-inside.me/) my-self to host my own files and my friends too!
The picture below is just an example from another Project!

![image](https://user-images.githubusercontent.com/11579313/160313562-9cbf422d-db66-4b0a-8bcd-7addbb0cda09.png)

**Comment by diced** [comment]
Yep, this will be included in the next version alongside many other features!

**Comment by Kadantte** [comment]
Thanks for considering this feature 😄

**Comment by diced** [comment]
It has been added in the newest release!
