### ISSUE TITLE
Delete image does not work

### ISSUE THREAD

**Issue by chamburr** [dicedtomatoreal/typex#139]
The delete image feature only removes the entry from the database, and the actual file does not get deleted. Furthermore, the endpoint would return with an internal server error, indicating the operation has failed.

As far as I can tell, the issue arises from the following code, where `config.uploader.directory` is undefined. I think there should also be separate logic to handle the different data sources?

https://github.com/diced/zipline/blob/b26fef3ad430d57775d4c3aeaacbc394c70ee984/src/pages/api/user/files.ts#L22

**Comment by diced** [comment]
Fixed in https://github.com/diced/zipline/commit/be9523304ac4e707ccb39243193d6083a0739775
