### ISSUE TITLE
The most bizzare issue I've encountered

### ISSUE THREAD

**Issue by ghost** [dicedtomatoreal/typex#141]
I've setup zipline through docker-compose and gave everything the right permissions. I'm using nginx for the webserver and I have SSL sertificates setup through certbot.
Files upload just fine and opening them through domain.net/r/name.ext works 100% of the time. However I can't say the same for  domain.net/u/name.ext...
What I noticed is sometimes the image will not have the width parameter set properly thus the image isn't rendered. Usually in this case refreshing the page with SHIFT+F5 fixes the issue and width gets set just fine, however F5 will break it again.
I have 0 clue on how to tackle this, it's probably cache related, but I'd really appreciate any help!

**Comment by ghost** [comment]
Saw a similar issue to this that got closed without any comments... what happened there?..

**Comment by diced** [comment]
Could you provide more details such as the version you're running, the browser you use, and the request you make to upload files? (Headers, etc and hide private info)

**Comment by ghost** [comment]
The version is 3.4.3 and I use google chrome.
For the upload I'm just using sharex, so I use the generated sxcu file. 

`
{
	"Version": "13.2.1";
	"Name": "Zipline",
	"DestinationType": "ImageUploader, TextUploader",
	"RequestMethod": "POST",
	"RequestURL": "https://cdn.hvh.tf/api/upload",
	"Headers": {
		"Authorization": "epictoken",
		"Embed": "true"
	},
	"URL": "$json:files[0]$",
	"Body": "MultipartFormData",
	"FileFormName": "file"
}
`

**Comment by ghost** [comment]
Seems to happen on firefox too, btw.

**Comment by ghost** [comment]
Not going to make a separate issue for this because it's a pretty minor question but is it possible to change up the site while using the docker-compose method of installation? I've tried to add some custom functionality but I see no changes after typing out "docker-compose down" and "docker-compose up". I obviously tried looking up stuff on the internet but none of it helped me sadly.

**Comment by diced** [comment]
> Not going to make a separate issue for this because it's a pretty minor question but is it possible to change up the site while using the docker-compose method of installation? I've tried to add some custom functionality but I see no changes after typing out "docker-compose down" and "docker-compose up". I obviously tried looking up stuff on the internet but none of it helped me sadly.

You will have to run the `docker:build-dev` npm script which uses the `docker-compose.dev.yml` which can build a new image. The script just does `docker-compose --file docker-compose.dev.yml up --build` if you do not want to use/install npm.

**Comment by diced** [comment]
@relaxtakenotes Regarding the first issue here, I'm not able to reproduce this by uploading an image with the Embed header, the image seems to view fine in multiple chromium-based browsers and Firefox. If possible could you send a screen recording of everything? If not providing more info through screenshots would be viable or a very detailed text explanation.

**Comment by ghost** [comment]
> @relaxtakenotes Regarding the first issue here, I'm not able to reproduce this by uploading an image with the Embed header, the image seems to view fine in multiple chromium-based browsers and Firefox. If possible could you send a screen recording of everything? If not providing more info through screenshots would be viable or a very detailed text explanation.

Alright, here: https://streamable.com/urlffz
I still suspect it's cache related so I'll try to disable caching in my nginx config and see what happens.

**Comment by ghost** [comment]
nope, disabling cache didnt help, unfortunate

**Comment by ghost** [comment]
Since now I'm able to make modifications to the source code I decided to see what could go wrong in the code.
I looked into the [...id].tsx file and logged these values: original.width, imageEl.width, original.src.
original.width and imageEl.width sometimes become 0, but original.src is correct. IDK why that happens though.

**Comment by ghost** [comment]
I commented out the part which changes the width of the image element, works for now I suppose?.. Not gonna close the issue just yet because it's weird behaviour.

**Comment by ghost** [comment]
Pretty sure I just fixed it myself... I don't get the issues I described after I changed up the updateImage function in src/pages/[...id].tsx
```
  const updateImage = () => {
    const imageEl = document.getElementById('image_content') as HTMLImageElement;
    const img = new Image();
    img.addEventListener("load", function() {
      if (this.naturalWidth > innerWidth) imageEl.width = Math.floor(this.naturalWidth * Math.min((innerHeight / this.naturalHeight), (innerWidth / this.naturalWidth)));
      else imageEl.width = this.naturalWidth;
    });
    img.src = dataURL('/r');
  };
```
From what I can tell the image gets loaded too slow and the function just has nothing to work with, so sometimes it needs to wait until it's loaded.

**Comment by diced** [comment]
I see, could you make a PR out of this?

**Comment by ghost** [comment]
yea sure

**Comment by ghost** [comment]
@diced https://github.com/diced/zipline/pull/143
