### ISSUE TITLE
Storage drivers

### ISSUE THREAD

**Issue by Kadantte** [dicedtomatoreal/typex#144]
Hello again! Is there a way to make Zipline support `Storage drivers`? I mean that instead of saving the data into docker `volumes` it saves the Data into `Storage drivers` for example: `Amazon S3` `FTP` `Google Cloud Storage` `Azure Blob Storage` at least if it can on an FTP!
You might be thinking why I asked for this since a lot of VPS don't come with that big storage and if it comes with more storage you need to pay more instead of storage boxes like this one [BX11](https://www.hetzner.com/storage/storage-box/bx11) from hetzner way cheaper. this Box has 1 TB of storage for 3.14$.

Here's mine:

![image](https://user-images.githubusercontent.com/11579313/163734099-00d224f7-b693-4f30-8c26-50fa3b872f8e.png)

**Comment by diced** [comment]
This functionality already exists, yet only for amazon's s3. Feel free to make a PR to add another!
