### ISSUE TITLE
Support for subpath

### ISSUE THREAD

**Issue by chamburr** [dicedtomatoreal/typex#148]
Zipline currently doesn't work on a subpath. I hope support for subpath can be added, thank you!

**Comment by diced** [comment]
Unfortunately, I will not be adding this. This can be done through NGINX easily.

**Comment by ghost** [comment]
> This can be done through NGINX easily.

For future reference this not true. The NGINX part *is* easy (see the Readme) but zipline won't work on a subpath unless you also:

- Change the NextJS base URL.
- Change all Zipline api requests to include the base URL.
- Change URL for the dashboard page.
- Probably other things?

You then have to rebuild zipline.

Dev advice on discord is to use a subdomain, so either do that or use [something else](https://github.com/awesome-selfhosted/awesome-selfhosted#file-transfer---single-click--drag-n-drop-upload).
