### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by schmayterling** [dicedtomatoreal/typex#155]
I've been searching in Issues and the docs but I can't seem to find documentation on the following features:
- Password Protected Uploads
- URL Formats (uuid, dates, random alphanumeric, original name, zws)

do you guys have any idea on how i may use these?

**Comment by diced** [comment]
Yep, sorry about the documentation I haven't really bothered updating it as much.

Password protected uploads work like this:
Add the `password` header when uploading a file with your desired password, when people use the link returned by the request it will ask them to enter a password and the rest is self explanitory

URL Formats also work the same way, you add the `format` header which can be `UUID`, `DATE`, `RANDOM` (default), or `NAME`. Date just formats the file like this: `YYYY-MM-DD_HH:mm:ss`, RANDOM just creates a string of alphanumeric characters with the length specified in your config, uploader.length or UPLOADER_LENGTH (environment var). Name just uses the original name returned in the request.

**Comment by mterlyn** [comment]
It's okay, don't stress too much on it :)
Thanks for the help! I've been stumped on it for quite a while now.
