### ISSUE TITLE
404 Not Found when route = ''

### ISSUE THREAD

**Issue by schmayterling** [dicedtomatoreal/typex#156]
The other routes are working as intended, but when I set the `[urls]` 's route to 	`route = ''`, it always returns a 404.

Expected Behavior:
- Accessible Link: ex. domain/randomlinkhere

What happens: 
- 404 Not Found

**Comment by diced** [comment]
urls.route is for shortened links and setting it to `''` basically tells it to serve on the root url which is used other other stuff. I would advise you to just use something like `/go` which is the default

**Comment by mterlyn** [comment]
I see. 
It'd be cool though as it allows for more personalization, but yeah, I might leave this issue up because I want to try making it a possibility at least.
