### ISSUE TITLE
Login Screen moves on wrong password

### ISSUE THREAD

**Issue by HPaulson** [dicedtomatoreal/typex#16]
### Issue
-  When entering an incorrect password on the login screen, the username, password, and login text all shift upward when the "Incorrect Password" message appears, Making a weird animation that is not clean and looks very ugly

### Solution
- Make the text and input's stay put while the "incorrect password" prompt appears

**Comment by dicedtomatoreal** [comment]
Known issue, 99% sure its a Swal issue, and I'll try finding issues because I've been lazy lmao

**Comment by dicedtomatoreal** [comment]
And what do you mean by "an animation that is not clean and looks very ugly" and you talking about the document shifting up while the alert stays in position?

**Comment by HPaulson** [comment]
Correct, although it is not intentional (it seems), the input box and header moving creates an animation-like move, which looks extremely ugly. In theory it should just stay in place.

**Comment by dicedtomatoreal** [comment]
Could you link or attach a gif of this happening

**Comment by dicedtomatoreal** [comment]
This is fixed on the latest update.
