### ISSUE TITLE
Files that are not images are not listed in Files view

### ISSUE THREAD

**Issue by zodiacg** [dicedtomatoreal/typex#160]
In the files view (/dashboard/files), only images are listed in a preview style. Text files/archives are only available from Home screen. Though the design of home screen isn't dedicated for listing files.

**Comment by diced** [comment]
Images, videos and audio files are also listed, and I am working on revamping this system to support text files (even uploading text sort of like hastebin and pastebin, etc instead of uploading a file which can be annoying). For archives I guess I could just show a icon for them, not sure though.

**Comment by zodiacg** [comment]
I see. I happened to integrate a newly installed zipline instance in some shell scripts to upload logs, thus didn't notice the support for video/audio.

**Comment by diced** [comment]
Zipline now has the ability to show all files whether its media or not in the latest commit!
