### ISSUE TITLE
Stats page is broken

### ISSUE THREAD

**Issue by Retr0-01** [dicedtomatoreal/typex#163]
After the recent update (HEAD at https://github.com/diced/zipline/commit/12baadd563847d5454ce13da7e997e9ca20d5820) the user stats page (``domain.com/dashboard/stats``) is completely broken, giving out a "Something went wrong..." page and the following client errors in the console:

![chrome_bcojSH8iKj](https://user-images.githubusercontent.com/61121754/180166713-730acb5c-2648-4d79-82c4-eefd9dc95e35.png)

**Comment by diced** [comment]
I see what happened here, and unfortunately I'm out of town so I won't be able to fix this for a bit. By next week it should be fixed.

**Comment by diced** [comment]
Fixed in latest update
