### ISSUE TITLE
Feature Request: Custom Quota Limits?

### ISSUE THREAD

**Issue by snaildos** [dicedtomatoreal/typex#164]
Setting Quota per user?

**Comment by diced** [comment]
Could you elaborate, a quota on what?

**Comment by superintendent2521** [comment]
quota on how much storage/uploaded images/pastes

**Comment by TacticalTechJay** [comment]
Are you referring to something similar to the variable `UPLOAD_USER_LIMIT` but more specific to the individual user?

**Comment by diced** [comment]
Closing as I don't see this as a useful feature, feel free to fork and add it in yourself.

**Comment by snaildos** [comment]
Well, it is a useful feature to prevent people uploading billions of files flooding your storage.
