### ISSUE TITLE
Discord Webhook Error

### ISSUE THREAD

**Issue by vincethepro** [dicedtomatoreal/typex#166]
When the discord webhook run's the embed shows "example: https://imageserver.com/u/KvdoxU.png" but that has CSS on that page so it needs to be "example: https://imageserver.com/r/KvdoxU.png" for it to work

**Comment by vincethepro** [comment]
anything?

**Comment by superintendent2521** [comment]
seems like all the dev needs to do is to change the Variable so rather than it using the image with css it should just use the raw image

**Comment by vincethepro** [comment]
that is what I said in a way

**Comment by diced** [comment]
Should be fixed in upstream, if using docker feel free to change from `latest` to `trunk` tag.
