### ISSUE TITLE
Internal server error when attemption to delete a file.

### ISSUE THREAD

**Issue by AjisaiMirai** [dicedtomatoreal/typex#168]
Whenever I'm trying to delete a file from the dash, a HTTP 500 status is returned. 
Console log:
files:1          Failed to load resource: the server responded with a status of 500 ()
VM61:1 Uncaught (in promise) SyntaxError: Unexpected token 'I', "Internal S"... is not valid JSON
829-ca4ef673f807d1be.js:1          DELETE https://domain.com/api/user/files 500

EDIT: ZWS has been enabled for these uploads.

**Comment by ItzDerock** [comment]
check the zipline application logs, not the browser logs.
