### ISSUE TITLE
Feature Request: Edit Text Files 

### ISSUE THREAD

**Issue by ar065** [dicedtomatoreal/typex#175]
I'm not sure if this is possible, but the ability to edit text files would be very nice

**Comment by diced** [comment]
This is possible, though I think it wouldn't be in the scope of what Zipline will do, so unfortunately I won't be adding this.

**Comment by raxod502** [comment]
Note: If it becomes necessary to edit a text file after upload, one can do it simply by editing the file directly in the storage location, and then editing the database record for that file to update the `size` column to match the new file size in bytes, if it has changed.

I believe you could do the same with any other file type, but additional steps might be needed to trigger updates of things like thumbnails.

**Comment by raxod502** [comment]
@diced Just curious, what makes you say this is out of scope for Zipline? It's not terribly unusual for pastebins to allow changing contents after upload (GitHub Gist allows this, for example), and it seems like a feature relatively in line with the current architecture of the project. Additionally it seems like the implementation wouldn't be too complex, as the user interface would be basically the same as initial upload, and only minimal work is needed to trigger recomputation of derived data like filesize and thumbnails.

**Comment by diced** [comment]
> [@diced](https://github.com/diced) Just curious, what makes you say this is out of scope for Zipline? It's not terribly unusual for pastebins to allow changing contents after upload (GitHub Gist allows this, for example), and it seems like a feature relatively in line with the current architecture of the project. Additionally it seems like the implementation wouldn't be too complex, as the user interface would be basically the same as initial upload, and only minimal work is needed to trigger recomputation of derived data like filesize and thumbnails.

yea, this was almost 4 years ago where it kinda didn't do all that stuff but it's evolved now and i guess makes sense to be able to do something like that. since you have pr'ed before, if you are thinkng of that: the way i'd impl this is just having like a patch route /api/user/files/:id/edit, having it on /api/user/files/:id's patch route might make shit confusing and annoying in code so yea.. otherwise lowkey imma add this to the roadmap for the next release

**Comment by raxod502** [comment]
I'm not quite at the place yet where I am able to contribute a whole user interface implementation, but I did develop a quick script that lets me edit files in my Zipline instance from the command line. Really, this isn't a general-purpose solution, but it does solve the problem right away for me. There are a couple of customizable variables at the top but if your deployment differs too much from mine you might have to change other things, too.

<details>

```python
#!/usr/bin/env python

import argparse
import atexit
from contextlib import closing
import csv
import hashlib
import io
import os
import shlex
import signal
import socket
import subprocess
import sys
import tempfile
import time
from typing import cast

# Shell command that prints the zipline postgres password
PASSWORD_CMD = ["pass", "..."]

# Name of host in your ~/.ssh/config for zipline server
SSH_HOST = "..."

# Relative path from home on zipline server to uploads directory
UPLOADS_DIR = "..."

def get_free_port() -> int:
    with closing(socket.socket()) as s:
        s.bind(("", 0))
        return s.getsockname()[1]


def is_listening(port: int) -> bool:
    with closing(socket.socket(socket.AF_INET, socket.SOCK_STREAM)) as s:
        return s.connect_ex(("127.0.0.1", port)) == 0


parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers(required=True)
parser_edit = subparsers.add_parser("edit")
parser_edit.add_argument("filename")
args = parser.parse_args()

filename = cast(str, args.filename)
if filename.startswith("https://"):
    filename = filename.split("/")[-1]
if "/" in filename or filename.startswith("."):
    raise RuntimeError(f"Bad filename: {filename}")

pgpass = subprocess.run(
    PASSWORD_CMD,
    check=True,
    stdout=subprocess.PIPE,
    encoding="utf-8",
).stdout.strip()

port = get_free_port()
ssh = subprocess.Popen(
    [
        "ssh",
        "-oControlPath=none",
        "-L",
        f"127.0.0.1:{port}:127.0.0.1:5432",
        "-N",
        SSH_HOST,
    ],
    stdin=subprocess.DEVNULL,
    stdout=subprocess.DEVNULL,
)

atexit.register(ssh.terminate)

connect_deadline = time.time() + 15
while not is_listening(port):
    if time.time() > connect_deadline:
        raise RuntimeError("ssh did not forward port, timed out")
    time.sleep(1)

psql = lambda query, fields=[], variables={}: list(
    csv.DictReader(
        io.StringIO(
            subprocess.run(
                [
                    "psql",
                    "-h",
                    "127.0.0.1",
                    "-p",
                    f"{port}",
                    "-U",
                    "zipline",
                    "--tuples-only",
                    "--csv",
                    *(f"--set={key}={val}" for key, val in variables.items()),
                ],
                check=True,
                env={**os.environ, "PGPASSWORD": pgpass},
                stdout=subprocess.PIPE,
                encoding="utf-8",
                input=query,
            ).stdout
        ),
        fields,
    )
)

db_records = psql(
    "SELECT id, size FROM \"File\" WHERE name = :'filename'",
    ["id", "size"],
    {"filename": filename},
)

if len(db_records) == 0:
    raise RuntimeError(f"No such file on Zipline: {filename}")
if len(db_records) > 1:
    raise RuntimeError(
        f"Multiple matches ({len(db_records)}) for file on Zipline: {filename}"
    )

(db_record,) = db_records
db_id = db_record["id"]
db_size = int(db_record["size"])

filename_stem, filename_ext = filename.split(".", 1)
temp_fileno, temp_filename = tempfile.mkstemp(
    prefix=filename_stem, suffix=f".{filename_ext}"
)
os.close(temp_fileno)

subprocess.run(
    ["scp", f"{SSH_HOST}:{UPLOADS_DIR}/{filename}", temp_filename],
    check=True,
)

if os.path.getsize(temp_filename) == 0:
    raise RuntimeError("Failed to download existing file")

old_size = 0
with open(temp_filename, "rb") as f:
    h = hashlib.sha256(usedforsecurity=False)
    while chunk := f.read(1024 * 1024):
        h.update(chunk)
        old_size += len(chunk)
    old_hash = h.hexdigest()

if old_size != db_size:
    print(
        f"warn: File size {old_size} does not match size {db_size} stored in db",
        file=sys.stderr,
    )

subprocess.run([os.environ.get("EDITOR", "vim"), temp_filename], check=True)

new_size = 0
with open(temp_filename, "rb") as f:
    h = hashlib.sha256(usedforsecurity=False)
    while chunk := f.read(1024 * 1024):
        h.update(chunk)
        new_size += len(chunk)
    new_hash = h.hexdigest()

if old_hash == new_hash:
    print("No changes, skipping re-upload", file=sys.stderr)
    sys.exit(0)

subprocess.run(
    ["scp", temp_filename, f"{SSH_HOST}:{UPLOADS_DIR}/{filename}.tmp"],
    check=True,
)

subprocess.run(
    [
        "ssh",
        SSH_HOST,
        f"mv {UPLOADS_DIR}/{shlex.quote(filename)}.tmp {UPLOADS_DIR}/{shlex.quote(filename)}",
    ],
    check=True,
)

if new_size != db_size:
    psql(f'UPDATE "File" SET size = {new_size}')
```

</details>
