### ISSUE TITLE
Docs: Specify URL endpoints for various uploaders

### ISSUE THREAD

**Issue by IngwiePhoenix** [dicedtomatoreal/typex#176]
I went and read it up from the source code to figure out how to configure ShareX to allow me to shorten URLs - however, others might not be so savy :)

Hence, I'd like to request an Endpoints section in the docs, pointing out which URLs are used for what.

For those curious:
![image](https://user-images.githubusercontent.com/2893716/189914617-6868a11f-da5b-417f-8e4a-dfe0081a6fe7.png)

There's probably more methods I didn't spot yet, tho...

Thanks and kind regards!

**Comment by diced** [comment]
The docs used to have this, I don't know why I forgot to add it in the new docs.. My bad, It will probably be included when 3.6 or 3.5.2 comes out.

**Comment by diced** [comment]
They are now included in the docs.
