### ISSUE TITLE
[Request] File Statistics

### ISSUE THREAD

**Issue by WinterFe** [dicedtomatoreal/typex#181]
It would be nice to list the file views as a statistic when you click your file in `/files`
i.e. here: http://dash.lunardev.group/u/0NrXRK.png

Also maybe an addition to statistics to see accumulated views per user based on all uploads? (something like a leaderboard)

Making admins not be able to delete other admin accounts
Under `/invites` when an invite is used and marked as "(Used)" maybe add some text to say who it was used by?

Another suggestion; allow configuration for using SMTP email servers, per say I have my own email servers and I'd like to use it here for notifications, registrations, etc

**Comment by diced** [comment]
Unfortunately, emails and other things like that are probably out of the scope for what Zipline can and should do so I do not have any plans on adding any sort of functionality with it.

Invites already say (Used) next to the code if they are used, although I won't be adding a field that says who used it as used invites get cleared out by a background task (defaults to 30m).
