### ISSUE TITLE
[Suggestion] Discord OAuth

### ISSUE THREAD

**Issue by WinterFe** [dicedtomatoreal/typex#184]
Add the option to link your Discord account to your zipline account with Discord OAuth after registration in the account page

**Comment by MrMysterius** [comment]
General OpenID / OAuth would be best, so you are not limited to Discord and something like Keycloak is also allowed.

**Comment by WinterFe** [comment]
In a more broad term allowing account connections *like* discord, or any other oauth

**Comment by WinterFe** [comment]
Already planned
