### ISSUE TITLE
[Suggestion] Naming

### ISSUE THREAD

**Issue by WinterFe** [dicedtomatoreal/typex#187]
Replacing the word 'images' with 'files' in multiple places that just make sense:

`dashboard/stats` - **Images** -> **Files** 

When uploading an image or file the loading toast in the bottom right should change from "uploading images" to "uploading files", considering that multiple file types are supported and its not always just images.

"Upload Successful
Copied first image to clipboard!"
-> "Upload Successful
Copied first file to clipboard!"

Etc.

**Comment by axisiscool** [comment]
lets go issue number 7!!!
