### ISSUE TITLE
[Issue] Exporting data does not work

### ISSUE THREAD

**Issue by WinterFe** [dicedtomatoreal/typex#189]
Issue: https://i.winterfe.xyz/u/CYMP6h.gif

Browser console: https://i.winterfe.xyz/u/FlVHHp.png
Application console does not provide any errors or warnings on this

**Comment by diced** [comment]
Unable to reproduce this error, does this happened right after an export has been made?

**Comment by TacticalTechJay** [comment]
Is there any context to what you did that could have caused the error?

**Comment by WinterFe** [comment]
I just started the export, clicked the link, brings me to the "Something went wrong screen".

Refreshing on this screen downloads the ZIP file, though it's completely empty
Other than the error in the screenshot in the original comment, there's nothing else I can provide

**Comment by JackBailey** [comment]
I'm running into the same issue

**Comment by TacticalTechJay** [comment]
What type of db and datasource are you using?

**Comment by JackBailey** [comment]
Using the default docker-compose.yml file - no changes made other than the port

**Comment by diced** [comment]
What operating system are you guys using? Linux, Mac, windows?

**Comment by JackBailey** [comment]
Linux - Ubuntu 20.04

**Comment by WinterFe** [comment]
Linux - Ubuntu 20.04
Datasource: S3
DB: PostgreSQL

**Comment by TacticalTechJay** [comment]
@WinterFe can you check on the db where an image does not have a `created_at`. You can use the below snippet for querying.

`SELECT * FROM "Image" WHERE created_at IS NULL;`

**Comment by WinterFe** [comment]
> @WinterFe can you check on the db where an image does not have a `created_at`. You can use the below snippet for querying.
> 
> `SELECT * FROM "Image" WHERE created_at IS NULL;`

@TacticalTechJay There are no images where created_at is null:
Looking further there isnt a single null value where there shouldnt be one

![image](https://user-images.githubusercontent.com/42700057/196297060-96792656-36e4-4087-8d5b-a52eebcb37bb.png)

**Comment by diced** [comment]
Just to confirm you do have files right? `SELECT * FROM "Image";`

**Comment by TacticalTechJay** [comment]
@JackBailey, are you able to try the above as well?

**Comment by WinterFe** [comment]
> Just to confirm you do have files right? `SELECT * FROM "Image";`

@diced yea, i’ve got just about 800 files lol

**Comment by TacticalTechJay** [comment]
Is the issue still present in new exports? Does the export exist in your temp dir(/temp)? If it does, are you able to check if there is any content and if it matches well with your uploads.

**Comment by WinterFe** [comment]
Fixed in commit: 3bf43f1606a12dc8c39df5169cf26051e40e84d9
([fix: maybe fix exports](https://github.com/diced/zipline/commit/3bf43f1606a12dc8c39df5169cf26051e40e84d9))
