### ISSUE TITLE
[Suggestion] Embed Variables

### ISSUE THREAD

**Issue by WinterFe** [dicedtomatoreal/typex#190]
Show variables on manage user page in a (by default) collapsed zone (similar to favorite images) that have a list of up-to-date embed variables rather than having users go to a separate website (docs) for the vars

Location: Either at the top where the text `"Want to use variables in embed text? Visit [the docs](https://zipline.diced.tech/docs/guides/variables) for variables"` is, or at the very bottom under the script generate buttons

**Comment by diced** [comment]
Rather keep the manage page less complicated and have all the information one needs in one place (the docs). It isn't really that much of a stretch to go to an external website to see how variables work.
