### ISSUE TITLE
[Issue] Creating multiple invites limit broken

### ISSUE THREAD

**Issue by WinterFe** [dicedtomatoreal/typex#195]
No need to explain: 
![xOnVfZP](https://user-images.githubusercontent.com/42700057/196149572-a6f98ad3-de1d-41d8-84c7-3a88bd775f23.png)

**Comment by TacticalTechJay** [comment]
The limit was changed to 100. Must've forgotten to change the text too...

**Comment by WinterFe** [comment]
lmao, then yea gotta change the text
