### ISSUE TITLE
[Suggestion] Show the original URL alongside vanity in dashboard

### ISSUE THREAD

**Issue by maximmax42** [dicedtomatoreal/typex#203]
Self-explanatory. It can be right below the vanity in the card, or, as an alternative, the go button can link directly to the original URL instead of shortened one.

**Comment by diced** [comment]
Great idea, hope to add this when 3.6.0-rc4 is out.

**Comment by diced** [comment]
Added in https://github.com/diced/zipline/commit/3df94526b007f9664896d9cac2b0aec067db502d along with many other stuff added to the URL card.
