### ISSUE TITLE
Bug: `UPLOADER_ROUTE`, while set, returns 404 error page

### ISSUE THREAD

**Issue by freegamerskids** [dicedtomatoreal/typex#206]
### What happened?

Hello. I have my `UPLOADER_ROUTE` env. variable set to `/u` (default). Upon accessing the site you'll get a 404 error page. Not sure what causes the problem.

[picture](https://prd.lol/view/svC3at.png)

### Version

upstream

### What browser(s) are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Browser Logs

```shell
Failed to load resource: the server responded with a status of 404 ()
```

**Comment by diced** [comment]
If you are just adding `/u` nothing will happen.

**Comment by freegamerskids** [comment]
Yeah, I know that. But when I go to the page, it just doesn't work.

**Comment by diced** [comment]
It's not supposed to return anything? What URL are you accessing, if its just `/u` like I said its expected behavior since there is no file in the URL (`/u/something.png`). If you are accessing the actual site (`/dashboard`) its a different story.

**Comment by freegamerskids** [comment]
Ok, I fixed it. I just changed the `UPLOADER_ROUTE` var to `/view`.
