### ISSUE TITLE
Invite System

### ISSUE THREAD

**Issue by MurdleDev** [dicedtomatoreal/typex#209]
Hello. I have enabled the invite system on my zipline instance. It seems to work, but it does not prompt an invite on registration. Why does this happen? Is this intended?

**Comment by diced** [comment]
I'm unsure as to what you're referring to, could you provide more description as to what the issue is? If the issue is invites don't work when user_registration is turned off then it's not intended behavior and a fix should be out soon for it.

**Comment by MurdleDev** [comment]
Yeah, the issue was that, but it seems to be fixed, so ill close this issue.
