### ISSUE TITLE
Bug: File with max views gets deleted before getting shown

### ISSUE THREAD

**Issue by maximmax42** [dicedtomatoreal/typex#213]
### What happened?

Trying to access a file which has one view remaining results in a 404 page and the file getting deleted.

https://user-images.githubusercontent.com/2225711/199967091-8a33ef7b-ae95-45c8-a802-2320c61a9bdf.mp4

### Version

upstream

### What browser(s) are you seeing the problem on?

Chrome

**Comment by superintendent2521** [comment]
possible that sending in to a service like discord where discord caches the image for easier grabbing so it displays faster, that i could have counted that as a view and then once hit the view limit, it will delete it

**Comment by maximmax42** [comment]
Well I didn't send the link anywhere, I opened it right away.

**Comment by superintendent2521** [comment]
hmm. weird i dont know then. sorry

**Comment by diced** [comment]
It's because the views get updated before the image is actually served, so when you open it, it updates, then serves you the content. For things like Discord unfortunately there is nothing I can do about that, possibly checking user agents is one solution but I'm not sure.

**Comment by superintendent2521** [comment]
adding a way to make it so certain ips/domains do not count towards that max view would be cool but hard to implement
