### ISSUE TITLE
Bug: setting UPLOADER_ROUTE to / results in 404 for files

### ISSUE THREAD

**Issue by maximmax42** [dicedtomatoreal/typex#214]
### What happened?

Trying to access any file results in a 404 page. It used to work before 3.6.0. UPLOADER_ROUTE=/u works just fine though.

### Version

upstream

### What browser(s) are you seeing the problem on?

Chrome

**Comment by TacticalTechJay** [comment]
After looking into it, the upload can be found at `//:id`. Setting it to be NULL (`UPLOADER_ROUTE= `) will likely have it default to `/u`.

**Comment by TacticalTechJay** [comment]
Zipline is not intended to have the upload route at root (`/`).

**Comment by diced** [comment]
Fixed in https://github.com/diced/zipline/commit/a75b79065452ad006383f618508293f67a66f97e

Set the UPLOADER_ROUTE=/ and files will be available through that, ex. https://example.com/test.png
