### ISSUE TITLE
Bug: Custom Domains

### ISSUE THREAD

**Issue by lyrx2k** [dicedtomatoreal/typex#216]
### What happened?

I think there is a Bug in "Manage Account > Manage User > Domains"
If i set a domain there, all screenshots get a 404 return, is there a trick or just a bug?

### Version

upstream

### What browser(s) are you seeing the problem on?

Chrome

**Comment by diced** [comment]
Whats your config atm? Run `yarn scripts:read-config`

**Comment by lyrx2k** [comment]
> Whats your config atm? Run `yarn scripts:read-config`

I dont have yarn :c
What config do u mean the `docker-compose.yml` ?

**Comment by TacticalTechJay** [comment]
Alternatively, you can use `npm run scripts:read-config`. If you got that, what would be the output? Censor any sensitive info

Edit: it was npm not node

**Comment by lyrx2k** [comment]
my config is in the dc server, using via docker.. [dc msg](https://discord.com/channels/729771078196527176/729771079224131717/1040107560260354148)

**Comment by TacticalTechJay** [comment]
Is this issue still present in the latest version?

**Comment by diced** [comment]
Due to no response, and inability to reproduce on my end, this issue will be closed as stale. Feel free to reopen if this problem persists in the **latest** release (whether that be `trunk` or `latest`)
