### ISSUE TITLE
Bug: Invite Length

### ISSUE THREAD

**Issue by lyrx2k** [dicedtomatoreal/typex#218]
### What happened?

I just saw after creating a Invite key for 3 days, that the invite showing 53 years (perma)

### Version

upstream

**Comment by diced** [comment]
Does the issue persist after refreshing?

**Comment by lyrx2k** [comment]
Yea

**Comment by diced** [comment]
Fixed https://github.com/diced/zipline/commit/e00393936f65a6c22db5dc8ac5116b02d8db288c
