### ISSUE TITLE
Bug: File Size

### ISSUE THREAD

**Issue by lyrx2k** [dicedtomatoreal/typex#219]
### What happened?

Hey my Admin upload limit is 10gb, i can easy upload zip files with 2gb no problems atall, but iant upload a 5.6gb zip file..
is that a bug or is there a trick?

### Version

upstream

### What browser(s) are you seeing the problem on?

Chrome

### Zipline Logs

```shell
i dont think there is any error log :c
```

**Comment by diced** [comment]
It might be related to internet speed, memory issues, etc. It should be able to handle whatever it gets although I don't really test on files that are that big...

**Comment by lyrx2k** [comment]
> It might be related to internet speed, memory issues, etc. It should be able to handle whatever it gets although I don't really test on files that are that big...

well my root has a avg download from 900+ and upload 800+
my private network has avg 50mbit up so i dont think its a network issue atall.
i can just upload the file fine via ftp, no issues atall there. ^^

**Comment by WinterFe** [comment]
considering your home network speeds it’s probably just taking a while lol

**Comment by lyrx2k** [comment]
> considering your home network speeds it’s probably just taking a while lol

Well like i said, the upload via zip is NOT possible with that file size but via ftp its fine and fast.

**Comment by diced** [comment]
Fixed https://github.com/diced/zipline/commit/51cfb9062a3c55f4ac9a0185ac2379473388ed91
