### ISSUE TITLE
Bug: Can't run on linux/arm/v7

### ISSUE THREAD

**Issue by At-Heal** [dicedtomatoreal/typex#241]
### What happened?

Trying to install zipline on Raspberry Pi 400

Steps to reproduce:
Install docker and proceed to install zipline. Run docker-compose up -d and it errors after
`Pulling zipline (ghcr.io/diced/zipline:)...
latest: Pulling from diced/zipline
**ERROR:** no matching manifest for linux/arm/v7 in the manifest list entries`

### Version

upstream (ghcr.io/diced/zipline:trunk)

**Comment by diced** [comment]
Unfortunately, the rust alpine image does not support `linux/arm64/v7`, therefore I will not be officially supporting that specific architecture for docker builds.
