### ISSUE TITLE
Preserve the original file name when using name format different than Name

### ISSUE THREAD

**Issue by Adaliciously** [dicedtomatoreal/typex#245]
### What happened?

(I was unable to choose a different template than Bug report, even though README mentions that you accept feature requests)

I would like for zipline to save the original filename, so even when using a Format different than NAME, saving the file will result in file being saved with original filename. It could be possible with HTTP Content-Disposition header.

### Version

upstream (ghcr.io/diced/zipline:trunk)

**Comment by TacticalTechJay** [comment]
Feature requests were moved to discussions. Could you start a thread there and close this issue?
