### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by DIVISIONSolar** [dicedtomatoreal/typex#262]
### What happened?

`{file.filename}` outputs `{unknown_property}` on embeds.

Example: https://cdn.joshsevero.dev/u/Kvmolw.png

### Version

latest (ghcr.io/diced/zipline:latest)

### Zipline Logs

```shell
There we no errors that I could see
```

**Comment by diced** [comment]
The property is `{file.file}` not `{file.filename}`. The docs are a bit outdated, sorry.

**Comment by DIVISIONSolar** [comment]
Ah, ok. Thanks that fixed it
