### ISSUE TITLE
Bug: vanity field at api/shorten endpoint should be optional / documented

### ISSUE THREAD

**Issue by IceToast** [dicedtomatoreal/typex#265]
### What happened?

When sending requests to the api/shorten endpoint the vanity field is required. However to let the server handle the vanity generation you can leave the field blank.

This behaviour should be documented like "Leave blank for auto generation..." or make it optional.

### Version

upstream (ghcr.io/diced/zipline:trunk)

**Comment by diced** [comment]
It is optional, and is now documented.
