### ISSUE TITLE
Bug: flameshot upload script always uploads the same file

### ISSUE THREAD

**Issue by OhaDerErste** [dicedtomatoreal/typex#267]
### What happened?

The auto generated flameshot config for wayland always uploads the same file

### Version

latest (ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox

### Additional Info

My config looks like this  
`#!/bin/bash
flameshot gui -p /tmp/ss.png;
curl -H "Content-Type: multipart/form-data" -H "authorization: XXXXXXXXX" -F file=@/tmp/ss.png https://ohaa.xyz/api/upload -H "Embed: true" | jq -r '.files[0]' | tr -d '\n' | wl-copy;`

**Comment by Zyztem** [comment]
It seems like its not deleting the temp file, ik the solution, it would be `rm -rf /tmp/ss.png`, i just dont know where to put it in this script. its strange its not overwriting the file.

**Comment by OhaDerErste** [comment]
Put it on top of the script and it works now

**Comment by diced** [comment]
Seems like the `-p` flag, when run again it produces a different file instead of overwriting, for example, `/tmp/ss_1.png`.

**Comment by diced** [comment]
Fixed https://github.com/diced/zipline/commit/9bf098a93a2094d6c492e05cd3540370e2b72c45

Will use `-r > /tmp/ss.png` instead of -p
