### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by MC3DTHEReal** [dicedtomatoreal/typex#268]
### What happened?

A bug happened!

i host website on friends kellerpc bechause i can upload htm files and its opening in browser like website 😎
u want proof?
![image](https://user-images.githubusercontent.com/45328235/211644662-db1cbf73-70d1-4b35-87da-37bc619262c6.png)

### Version

upstream (ghcr.io/diced/zipline:trunk)

**Comment by Adaliciously** [comment]
is it really a bug? it's all clientside code, your browser just chooses to render it instead of downloading by default

**Comment by mc3dreal** [comment]
yeah because the dingsi bumsi normally opens code editor and there it downloads it as a website because it ends with .htm
and not with .html

**Comment by diced** [comment]
Going to close this. The file can be downloaded by adding the `?download=true` query string to the /r/ url, e.g. `/r/something.html?download=true`, will download the file without rendering it. This functionality is only available in the 3.7-rc's.
