### ISSUE TITLE
Inconsistency: Filename variable

### ISSUE THREAD

**Issue by maximmax42** [dicedtomatoreal/typex#275]
### What happened?

[Docs page on variables](https://zipline.diced.tech/docs/guides/variables) lists {file.filename} as the variable for the filename, but it doesn't work. Playground field at the bottom of the page says it's {file.file} and it only works in the playground. The actual variable that works is {file.name}.

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by maximmax42** [comment]
Also, offtopic, but I've [made a PR](https://github.com/diced/zipline-docs/pull/41) about a different docs issue to the repo 2 weeks ago that you didn't merge still.

Also also, is there a variable for the original file name if you use the Original-Name header?

**Comment by diced** [comment]
This change has not been documented yet as it is a part of the RC, once a full release comes out all changes will be listed under GitHub releases.

> Also, offtopic, but I've https://github.com/diced/zipline-docs/pull/41 about a different docs issue to the repo 2 weeks ago that you didn't merge still.

Thanks for the reminder, I'll do that soon

> Also also, is there a variable for the original file name if you use the Original-Name header?

Yes, it can be accessed via `{file.originalName}`

**Comment by maximmax42** [comment]
> Yes, it can be accessed via `{file.originalName}`

Hm. Doesn't seem to be working. Getting an {unknown_property} instead.

**Comment by diced** [comment]
Yeah, sorry about that. Now fixed, and embedded images should allow all variables except sensitive ones, (password, totpSecret)

https://github.com/diced/zipline/commit/9f534e18c8c395f51e10d1f1a87eb9861ab221ca

**Comment by maximmax42** [comment]
Doesn't seem to be working still, I'm afraid. Original filename is definitely saved in the db.

**Comment by diced** [comment]
Are you sure you are on the latest version?

**Comment by maximmax42** [comment]
Yeah, on trunk, just pulled the latest update.

**Comment by diced** [comment]
It has not built yet. https://github.com/diced/zipline/actions/runs/4020210944/jobs/6907877626

**Comment by maximmax42** [comment]
Ah. Oops.

**Comment by maximmax42** [comment]
Confirmed, works.
