### ISSUE TITLE
Bug: URL Shortner route

### ISSUE THREAD

**Issue by IceToast** [dicedtomatoreal/typex#276]
### What happened?

In this commit https://github.com/diced/zipline/commit/6d49463dad16ce1369dab2b1366ccfe57379b537 you put in the wrong config. 

It should be `zconfig.urls.route` instead of `zconfig.uploader.route`.

This results in a return URL from the api endpoint using the wrong route and thus redirects don't work.

### Version

upstream (ghcr.io/diced/zipline:trunk)

**Comment by TacticalTechJay** [comment]
#255 has it fixed

**Comment by diced** [comment]
Fixed
