### ISSUE TITLE
Bug: Uploaded date for files is invalid

### ISSUE THREAD

**Issue by maximmax42** [dicedtomatoreal/typex#278]
### What happened?

All (but one) of my files in the gallery show this instead of the actual date:
![image](https://user-images.githubusercontent.com/2225711/215078124-505ae77c-b0e9-4b3a-882e-a3ebdcedca11.png)
And one file shows this:
![image](https://user-images.githubusercontent.com/2225711/215079174-f9d7df33-e8fb-4536-b9b0-e11d572b04a1.png)
Except its actual upload date is this:
![image](https://user-images.githubusercontent.com/2225711/215079249-acd3260b-90f3-4512-8ebc-7cc1779fb861.png)

Something somewhere thinks that the date format is mm.dd.yyyy, even though both my host and my own pc use dd.mm.yyyy.

Dashboard's main page shows a proper upload date.

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment]
Not sure if this will fix it but, the path Zipline is on in the docker file is `/app` now, make sure your volumes use `/app` instead of `/zipline`.

**Comment by diced** [comment]
> Something somewhere thinks that the date format is mm.dd.yyyy, even though both my host and my own pc use dd.mm.yyyy.

That's weird... It should be using your browsers locale format, which i'm guessing is probably dd.mm.yyy

**Comment by maximmax42** [comment]
> Not sure if this will fix it but, the path Zipline is on in the docker file is `/app` now, make sure your volumes use `/app` instead of `/zipline`.

I tried a build before the 70c2fa8ef45a4a82fcc70edfbcd2f399218b2af5 commit, same thing. But thanks, that should probably fix the other issue I've opened.

> That's weird... It should be using your browsers locale format, which i'm guessing is probably dd.mm.yyy

Yup, dd.mm.yyyy everywhere.

**Comment by diced** [comment]
> Yup, dd.mm.yyyy everywhere.

Hold on, is it using that format, or are you just saying it should be using that?

**Comment by maximmax42** [comment]
It should be using dd.mm.yyyy, but somehow, and only in the gallery's file cards, it's trying to read a dd.mm.yyyy date as a mm.dd.yyyy.

**Comment by maximmax42** [comment]
Creation time in the URL card in the `/dashboard/urls` also shows just fine.

**Comment by maximmax42** [comment]
Update: 3.5.1 displays everything just fine, 3.6.0 and onwards doesn't. Might be the relative time package?

**Comment by TacticalTechJay** [comment]
Do you have any sample data of any image directly from the db that has this problem?

**Comment by maximmax42** [comment]
```
COPY public."File" (id, name, mimetype, "createdAt", views, "userId", favorite, embed, format, password, "expiresAt", "maxViews", "originalName") FROM stdin;
12	72mBg.txt	text/plain	2022-10-28 10:55:33.642	86	1	f	t	RANDOM	\N	\N	\N	\N
23	hciKJ.mp4	video/mp4	2022-11-04 12:04:46.088	3	1	f	t	RANDOM	\N	\N	\N	\N
```

First one shows "NaN years ago" and "Invalid Date", second shows "10 months ago" and "11.04.2022, 17:04:46".
My system format is dd.mm.yyyy everywhere, timezone is UTC+5.

**Comment by maximmax42** [comment]
I'm breaking my goddamn brain over this. I don't get it. Apparently `new Date('2022-11-04 12:04:46.088')` just doesn't produce a proper Date object. Is there any way to change the way how the dates are stored in the database to proper ISO 8601 (YYYY-MM-DDTHH:mm:ss.sssZ)?

**Comment by maximmax42** [comment]
Uh... I see what the problem is apparently. Why is `image.createdAt` in https://github.com/diced/zipline/blob/6955d83b0c6bc8c6bb585f37c8eb6407b879438e/src/components/File.tsx#L257 already a localized string (a la "23.02.2023, 19:04:11") instead of whatever format should be returned from the db? Is it because of this?https://github.com/diced/zipline/blob/6955d83b0c6bc8c6bb585f37c8eb6407b879438e/src/lib/queries/files.ts#L26 
Trying to do `new Date("23.02.2023, 19:04:11")` does indeed produce an incorrect date, but `new Date('2023-02-23 19:04:11.000')` would produce a proper date.

**Comment by TacticalTechJay** [comment]
You could try forking zipline and changing the end of this 
https://github.com/diced/zipline/blob/6955d83b0c6bc8c6bb585f37c8eb6407b879438e/src/lib/queries/files.ts#L26

to `toISOString()`.

**Comment by diced** [comment]
> Uh... I see what the problem is apparently. Why is `image.createdAt` in
> 
> https://github.com/diced/zipline/blob/6955d83b0c6bc8c6bb585f37c8eb6407b879438e/src/components/File.tsx#L257
> already a localized string (a la "23.02.2023, 19:04:11") instead of whatever format should be returned from the db? Is it because of this?
> 
> https://github.com/diced/zipline/blob/6955d83b0c6bc8c6bb585f37c8eb6407b879438e/src/lib/queries/files.ts#L26
> 
> Trying to do `new Date("23.02.2023, 19:04:11")` does indeed produce an incorrect date, but `new Date('2023-02-23 19:04:11.000')` would produce a proper date.

Ah.. I see, it shouldn't be localized at all in the file query.

**Comment by maximmax42** [comment]
> You could try forking zipline and changing the end of this
> 
> https://github.com/diced/zipline/blob/6955d83b0c6bc8c6bb585f37c8eb6407b879438e/src/lib/queries/files.ts#L26
> 
> to `toISOString()`.

Surprisingly, that didn't help. But now I have this.
![image](https://user-images.githubusercontent.com/2225711/221006637-1cfb64cc-faa9-4e37-bca7-328220052bb7.png)

Guess it's not that line in particular. Trying line 42.

**Comment by maximmax42** [comment]
Okay, so, yeah. https://github.com/diced/zipline/blob/6955d83b0c6bc8c6bb585f37c8eb6407b879438e/src/lib/queries/files.ts#L42 and https://github.com/diced/zipline/blob/6955d83b0c6bc8c6bb585f37c8eb6407b879438e/src/lib/queries/files.ts#L53 need to be ISO strings. Or just untouched.

**Comment by diced** [comment]
Can you take a look at the above commit and see if it fixes the issues you have?

I've just removed the toLocaleString from all of them, and replaced with Dates.

https://github.com/diced/zipline/commit/fdcd1f3d28a7aefe6ac4452afdb962917188a081

**Comment by maximmax42** [comment]
> Can you take a look at the above commit and see if it fixes the issues you have?
> 
> I've just removed the toLocaleString from all of them, and replaced with Dates.
> 
> [fdcd1f3](https://github.com/diced/zipline/commit/fdcd1f3d28a7aefe6ac4452afdb962917188a081)

Yeah, this works. 
![image](https://user-images.githubusercontent.com/2225711/221170366-1782a1de-a940-4e6e-a5bd-ee0ddcee7a92.png)

Except there's this mess now:
![image](https://user-images.githubusercontent.com/2225711/221155575-74889903-d808-44fb-aa88-046ad2ed31b0.png)

**Comment by TacticalTechJay** [comment]
Hmm... I suppose that's a step.

**Comment by maximmax42** [comment]
So, e804d0b31e9420449de32fc39ede7b816da9f04f has fixed the previously mentioned mess, and it all looks nice.
![image](https://user-images.githubusercontent.com/2225711/221701844-5077ca0d-2551-491c-b0f6-eb052ef4d63d.png)

With that, I think this issue can be closed.

**Comment by diced** [comment]
Yep! Forgot to let you know yesterday, my bad. If there are any more problems after this feel free to post another comment and reopen.
