### ISSUE TITLE
Bug: /r/file.name and /favicon.ico return 404

### ISSUE THREAD

**Issue by maximmax42** [dicedtomatoreal/typex#279]
### What happened?

Either 9f534e18c8c395f51e10d1f1a87eb9861ab221ca or 70c2fa8ef45a4a82fcc70edfbcd2f399218b2af5 (probably latter) broke both /r/ links and /favicon.ico link. Docker build based on 55bd72aef88371f09494a30c21a8156fb6c1e49e works just fine.

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by maximmax42** [comment]
Fixed by replacing `/zipline` with `/app` in docker-compose.yml. I assume you'll only update the file  in the repo once you actually release this version.

**Comment by diced** [comment]
I'll be pushing another commit in a while that reverts back to /zipline, as it will probably be super annoying for people to migrate over. Be on the look out again!
