### ISSUE TITLE
Feature Request: Use different domain for URL shortener side

### ISSUE THREAD

**Issue by ItsNoted** [dicedtomatoreal/typex#284]
### What happened?

I'd like to use 2 domains. One domain for the files and text side and another domain specifically for short URLs.

### Version

latest (ghcr.io/diced/zipline:latest)

**Comment by diced** [comment]
The ability to override domains has been added in https://github.com/diced/zipline/commit/83718d7b312670e44c2f59390db3458876f82b7b. If there are any problems with that update feel free to reopen the issue!
