### ISSUE TITLE
Bug: image passwords ignoring hash character

### ISSUE THREAD

**Issue by Blooym** [dicedtomatoreal/typex#287]
### What happened?

After setting an image password, e.g. `Password`, a user can enter `Password#123` to unlock the image. From looking at the logs, I can see everything after the `#` character has been removed. I've attached a video demonstrating the issue.

[Kooha-2023-02-17-13-28-22.webm](https://user-images.githubusercontent.com/19539165/219665314-b783344d-038f-47b9-8344-375b721908a5.webm)

### Version

latest (ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox, Firefox Mobile

### Zipline Logs

```shell
info  [server::response] GET /api/auth/image?id=19&password=Password123 -> 400 // Did not use hashtag
info  [server::response] GET /api/auth/image?id=19&password=Password -> 200 // Hashtag used
```

**Comment by diced** [comment]
Seems like anything after the # character is ignored, leaving it a valid password as the request sent only contains `Password` (which is the correct password).

**Comment by diced** [comment]
Issue was that the password supplied in the query was not URL encoded, and the # is treated like an id attribute. It has been fixed in https://github.com/diced/zipline/commit/e1003d4bb67dd679776202202e42ea94ac329698
