### ISSUE TITLE
Bug: /api/shorten returns incorrect urls in :trunk version

### ISSUE THREAD

**Issue by spencerhooks** [dicedtomatoreal/typex#298]
### What happened?

I've been developing my extension using :latest and this works fine there. I tried :trunk today and the URLs returned by /api/shorten are incorrect. When generating a short URL the api should return something like:
https://host/go/short

However, what comes back via the api is:
https://host/ushort

The correct URL shows up in the dashboard of Zipline and it works from there.

I didn't have URLS_ROUTE set and was using the default, which worked on :latest. When things stopped working on :trunk I tried setting URLS_ROUTE=/go in my compose file, but nothing changed.

### Version

upstream (ghcr.io/diced/zipline:trunk)

**Comment by TacticalTechJay** [comment]
Are you trying this within a docker container or without? Are you certain that you're using the latest image or commit?

Because https://github.com/diced/zipline/commit/739f58492188ae069f23057ba3c68fcd56162f3c should have fixed it.

**Comment by spencerhooks** [comment]
I'm using a docker container with the image set to ghcr.io/diced/zipline:trunk. Definitely not sure I'm using the latest commit. Would this fix be in the latest image? or should I be testing in a different way?

**Comment by TacticalTechJay** [comment]
The latest image I'm referring to is the latest :trunk. It should have some new changes depending on how long ago you pulled the image

**Comment by spencerhooks** [comment]
I'll setup a new instance tomorrow and make sure it's the latest image. Will do some testing and report back.

**Comment by spencerhooks** [comment]
I setup a new instance of zipline on a different VM, this time using :trunk. This one is not going through external dns/proxy server, it's just on an internal domain. However,  on this instance when I try to copy the token the clipboard doesn't change. I've tried visiting this instance on both the IP address and the internal domain. Without the token I can't test against the bug that I raised.

**Comment by spencerhooks** [comment]
Ok, now that we figured how to solve my copy token problem: I can confirm that this is fixed in the version of :trunk that was pulled last night. So :trunk is now working via the api and this can be closed.
