### ISSUE TITLE
Bug: ShareX config returns non-SSL URL

### ISSUE THREAD

**Issue by TwoBrake** [dicedtomatoreal/typex#304]
### What happened?

When I upload an image with ShareX to Zipline with the configuration provided, it returns "http" rather than "https". This randomly started happening just a week ago, but was fine before.

Is there any way to fix this?

### Version

latest (ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox, Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc), Safari, Firefox Mobile, Safari Mobile

**Comment by Zyztem** [comment]
The config option `CORE_RETURN_HTTPS` seems to be missing. Here's the documentation for it. https://zipline.diced.tech/docs/config/core#core_return_https

**Comment by Zyztem** [comment]
And yes, it might be `CORE_HTTPS`, @diced could you confirm which one it is?

**Comment by diced** [comment]
its CORE_RETURN_HTTPS
