### ISSUE TITLE
Bug: Scroll bar at the bottom of the stats page

### ISSUE THREAD

**Issue by xSkeletor** [dicedtomatoreal/typex#312]
### What happened?

For some reason, there is a scroll bar at the bottom of the stats page that doesn't do anything (it can't be moved).

![image (1)](https://user-images.githubusercontent.com/58961555/222875012-c8fcff9b-0877-42b2-b382-823dcefa974c.png)

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment]
What is your display's size and browser viewport size?

To get viewport size:
```js
`${window.innerWidth}x${window.innerHeight}` 
````
![image](https://user-images.githubusercontent.com/35403473/222876297-93a054c9-4464-4e42-8f38-73511075ec57.png)

**Comment by xSkeletor** [comment]
1536x722. After playing around with the GUI of the developer console, changing the width sometimes makes the bar disappear and appear other times. The actual display size is 1920x1080.

**Comment by diced** [comment]
Not able to reproduce with a 1920x1080 display (with around the same viewport size). Not sure why this is happening.

**Comment by TacticalTechJay** [comment]
Closing this as stale.
