### ISSUE TITLE
Bug: Original filename isn't saved in UTF-8

### ISSUE THREAD

**Issue by maximmax42** [dicedtomatoreal/typex#317]
### What happened?
Steps to reproduce:
1. Upload a file with non-Latin letters in the name, for example: `тест.png`
2. Try to use {file.originalName}

Expected: `тест.png`
Actual: `ÑÐµÑÑ.png`

Checked the database, it gets saved with the wrong encoding there.

### Version

upstream (ghcr.io/diced/zipline:trunk)

**Comment by TacticalTechJay** [comment]
Does it affect zipline in any way? I saved the file with that original name and noticed no issues

**Comment by maximmax42** [comment]
I mean, it doesn't break Zipline, it just shows gibberish in the Discord embeds if you try to use the original filename.

**Comment by TacticalTechJay** [comment]
I see, thanks for clarifying the problem.
