### ISSUE TITLE
Bug: embed footer not showing on video embeds

### ISSUE THREAD

**Issue by Ollie1101** [dicedtomatoreal/typex#323]
### What happened?

when uploading an image the embed is displayed correctly, but on a video embed it does not show. (refer to the image)
![rvX3AS 1](https://user-images.githubusercontent.com/46160541/224515690-1bb47d3d-65df-4590-acf0-842f87b9d30c.png)

### Version

upstream (ghcr.io/diced/zipline:trunk)

**Comment by TacticalTechJay** [comment]
Are you referring to the text "uhm" in the image that doesn't appear with the video's embed?

**Comment by TacticalTechJay** [comment]
What is your current config for embeds?

**Comment by Ollie1101** [comment]
> Are you referring to the text "uhm" in the image that doesn't appear with the video's embed?

Yes


> What is your current config for embeds?

These are the settings im using
![image](https://user-images.githubusercontent.com/46160541/224543004-11c7287a-cdc9-4759-82bc-f3024b524ee8.png)

**Comment by TacticalTechJay** [comment]
Alright, I've tried my best to find out what could have broke but, it seems likely that it's a discord issue rather than zipline.
