### ISSUE TITLE
Bug: Zipline recommends to update to release candidate

### ISSUE THREAD

**Issue by nicotsx** [dicedtomatoreal/typex#327]
### What happened?

We recently got a message telling to update to latest version but it is tagged as an `rc`. Is it an intended thing?

![](https://user-images.githubusercontent.com/58747968/226460940-4bed5230-aca3-46e0-b6e3-d83c6babde00.png)

### Version

other (provide version in additional info)

### Additional Info

Zipline 3.6.4

**Comment by diced** [comment]
The stable version currently does not have a good version checking system, so it will just say that. The current upstream versions fix this issue, and will only tell you to update to an RC IF you are currently using and RC.

**Comment by nicotsx** [comment]
Thanks for your answer @diced
