### ISSUE TITLE
Bug: Message spam when pasting image

### ISSUE THREAD

**Issue by RappyTV** [dicedtomatoreal/typex#334]
### What happened?

When I paste an image in to the upload tab, I get a lot of messages saying that it was successfully pasted in.
http://files.rappytv.com/u/iPQiPs.mp4

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment]
Seems like the way I was creating the event was very wrong and created a listener like every time. Fixed 37e7ad840cf1d5f1089d60ce6b70e99ff4b6a920

**Comment by RappyTV** [comment]
it's still happening
