### ISSUE TITLE
Bug: Files don't delete from S3 endpoint.

### ISSUE THREAD

**Issue by NebulaBC** [dicedtomatoreal/typex#336]
### What happened?

I was testing a new script using zipline, and I was using quite big files for testing. So just out of curiosity I logged into Backblaze (my S3 provider) and I realized that even after deleting the uploaded files on the panel, they were still on my S3.

I'm guessing even if this is fixed I'll have to cross reference my S3 with Zipline's postgres, since I probably have a few hundred deleted files still on my S3.

### Version

upstream (ghcr.io/diced/zipline:trunk)

### Zipline Logs

```shell
Nothing of interest, even with debug on.
```

### Additional Info

Nothing interesting, just a basic S3 config
- DATASOURCE_TYPE=s3
- DATASOURCE_S3_ACCESS_KEY_ID=<>
- DATASOURCE_S3_SECRET_ACCESS_KEY=<>
- DATASOURCE_S3_ENDPOINT=s3.us-west-000.backblazeb2.com
- DATASOURCE_S3_BUCKET=neb-cx-zipline
- DATASOURCE_S3_PORT=443
- DATASOURCE_S3_USE_SSL=true

**Comment by diced** [comment]
I'm not able to reproduce this within my AWS S3 bucket, this might be a problem within backblaze's implementation?

**Comment by NebulaBC** [comment]
I'm pretty sure that backblaze's B2 is known as a pretty good implementation of S3. It's 10gb free without payment details though if you'd like to try on there. I'm not sure what the issue with my zipline setup could be since it's latest version.

**Comment by NebulaBC** [comment]
I decided to look into this more, and I found a file stored under the same name with the mimetype "application/x-bz-hide-marker". This sparked some curiosity, so I peeked around B2 documentation, and it looks like "Lifecycle Settings" are set by default to keep all files unlisted even after they're deleted, and to keep all revisions of a file.

**Comment by diced** [comment]
Interesting... Wonder if we should add some sort of thing like this to the FAQ, warning users that certain implementations could differ from provider to provider, etc.
