### ISSUE TITLE
Bug: Unable to upload video/mp4 mimetype with cURL.

### ISSUE THREAD

**Issue by NebulaBC** [dicedtomatoreal/typex#337]
### What happened?

When I try to upload a mp4 through the panel it works perfectly fine and shows mimetype as video.mp4, but when I try and upload with cURL I get `{"statusCode":415,"code":"FST_ERR_CTP_INVALID_MEDIA_TYPE","error":"Unsupported Media Type","message":"Unsupported Media Type: video/mp4; boundary=------------------------8abfc2e228ce909d"}`

### Version

upstream (ghcr.io/diced/zipline:trunk)

### Additional Info

I'm able to upload as multipart/form-data, but doing this doesn't allow the video to embed, and you can't preview the file.

**Comment by diced** [comment]
The upload type must be multipart/form-data, the API does not handle other content-types.

**Comment by NebulaBC** [comment]
Will this possibly change in the future, or could the server possibly detect and update the mimetype once the file is uploaded?

**Comment by diced** [comment]
It is unlikely that I will add support for that, but the mimetype not being recognized by Zipline seems to be a CURL problem.. I might make it so that it will try to detect the mimetype if it's using `application/octet-stream`.

**Comment by diced** [comment]
I've added the env variable `UPLOADER_ASSUME_MIMETYPES=boolean`, which can solve this issue. In it's response it will say what mimetype it assumed the file is.
