### ISSUE TITLE
Bug: Wrong statistics

### ISSUE THREAD

**Issue by RappyTV** [dicedtomatoreal/typex#338]
### What happened?

The statistics show the wrong amount of uploads: 
![image](https://user-images.githubusercontent.com/72705182/227184224-f4697682-a224-4f53-b521-330e3c30604b.png)
(also it shows ∞% next to the number)
even if I have 4 files uploaded:
![image](https://user-images.githubusercontent.com/72705182/227184332-32d70d18-1729-4388-add4-3fdaed7365ec.png)

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment]
The stats page will only update every 30 minutes, so it may take some time for the stats to become "correct" in a way.
