### ISSUE TITLE
Bug: Can't set file password correctly

### ISSUE THREAD

**Issue by RappyTV** [dicedtomatoreal/typex#341]
### What happened?

When I try to set the password in the file options, after every button I press it automatically selects the close button and the input field gets unselected so I can't continue typing and have to click into the field after every letter I enter.

https://user-images.githubusercontent.com/72705182/227190917-331d17e2-f863-4bab-bf7a-240280f59f96.mp4

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment]
This issue persists within versions before 3.7.0's RCs (it was fixed in one of the 3.7.0 RC's). Please make sure when making an issue you select the correct version, as you have selected "upstream" instead of stable.
