### ISSUE TITLE
Bug: Weird empty highlighted box in folders

### ISSUE THREAD

**Issue by xSkeletor** [dicedtomatoreal/typex#343]
### What happened?

When you have no folders and the list is empty, for some reason you can hover over something in the name category and then you can see its effect.

![image](https://user-images.githubusercontent.com/58961555/227742319-3d458255-08e6-44cc-bcf7-4f1693f0fd22.png)

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment]
Seems to be a bug with `mantine-datatable`, it isn't much of a problem as most people won't be hovering over that one area, if not even have no data within the tables.
