### ISSUE TITLE
Bug: URL shortener not copying URLs properly

### ISSUE THREAD

**Issue by xSkeletor** [dicedtomatoreal/typex#344]
### What happened?

As revealed before by @TacticalTechJay and fixed in most places by him, if the connection is not HTTPS then browsers will not allow them to access the clipboard. This was fixed by @TacticalTechJay places where there is a copy URL button, but it was not fixed here, in the modal that pops up after you created a shortened URL. Essentially, just make this popup say the same security error that other copy URL buttons do when you don't have an HTTPS connection.

![image](https://user-images.githubusercontent.com/58961555/227742570-7d43b549-1229-47fb-9811-a6b9ca381bd1.png)

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment]
Seems to be a bug with `mantine-datatable`, it isn't much of a problem as most people won't be hovering over that one area, if not even have no data within the tables.

**Comment by diced** [comment]
This seems quite tedious to replace every instance of this with a warning/alternative way. The reasons for clipboard copying failing are very rare edge cases that I feel most users do not fall under. It may be better just adding a FAQ statement about this.

**Comment by xSkeletor** [comment]
It looks like many places with a copy button should share a lot of the same code, so I'm not sure why only some of them were replaced with an added error security message and others weren't (the URL shortener, mainly). In any case, while it's necessary, I think it is nice to have instant feedback as to why it's not working, even if it's not an error that will occur that regularly, although it happens for me. An FAQ section could also be useful I guess, but having the default "URL has been copied message" appear when it's not working is a bit misleading, which is why I would prefer to have this fixed.

**Comment by TacticalTechJay** [comment]
> It looks like many places with a copy button should share a lot of the same code, so I'm not sure why only some of them were replaced with an added error security message and others weren't

I used Ctrl + F and Ctrl + V to cover most of my bases. Must've missed some places. 😔

**Comment by diced** [comment]
I've decided to remove every instance of the notification error. It seems like the only thing that needed to be replaced was copying your token - which I have added another way within the manage user page. Every other instance, you can just right click and copy link to clipboard, natively within your browser.

**Comment by xSkeletor** [comment]
This is a very poor design choice as this notification will now be misleading to people using HTTP instead of HTTPS, like if they only plan on hosting it on LAN and not making it public. You should at least add a message to the FAQ section on the website explaining why things may not copy correctly sometimes.
