### ISSUE TITLE
Bug: Extra space in list view formats for URLs/folders

### ISSUE THREAD

**Issue by xSkeletor** [dicedtomatoreal/typex#345]
### What happened?

As can be seen the by the screenshot below, when there's only 1 item in a list, there will be extra space below the first item in the list that will add space between the first element and then the border of the list. This looks to be only an issue in the URLs/folders lists, but the accounts list looks fine.

URLs/folders (broken):
![image](https://user-images.githubusercontent.com/58961555/227743143-c7ecfc51-1f28-4049-b55a-ec739f9f55cc.png)

Users (displaying properly with only 1 element):
![image](https://user-images.githubusercontent.com/58961555/227743196-585b5862-20bb-402f-8d7d-36120b45828b.png)

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment]
Originally I removed it, but decided to add it back in by making the tables take the entire width of the page.
