### ISSUE TITLE
Bug: Page Selection on Files Gallery Disappears when you delete the last item on the last page.

### ISSUE THREAD

**Issue by Gaurhoth** [dicedtomatoreal/typex#371]
### What happened?

Minor UI issue when you are on the Files tab (from sidebar). If you delete the last file on the last page of your files, the Page Selection navigation disappears, and the page is replaced with "Nothing here" message. This leaves you in a dead end with no consistent way to navigate to back to an early page.

Even hitting Browser Refresh (F5) just reloads the same "Nothing here" message (the url is still referencing an empty page). Clicking the Files Tab doesn't go back to first page and leaves you on the now empty page. 

To get back to a non-empty page, you either have to manually edit the page in the URL or click Files tab (which resets the URL) and then hit F5.

### Version

latest (ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Zipline Logs

```shell
No relevant events logged.
```

**Comment by diced** [comment]
Fixed https://github.com/diced/zipline/commit/d6ce64ae215a0141d2e00640b3a31906345daf33

When deleting the last item, it will go back to the previous page and repeat until the last image, where it will finally show that alert.
