### ISSUE TITLE
Bug: Filename with multiple dots get truncated

### ISSUE THREAD

**Issue by alexislours** [dicedtomatoreal/typex#384]
### What happened?

Uploading files that contain multiple `.` (dots) in their filename with the Format option set to "Original Name" will remove anything after the first dot.

Example:
- Create a file named `1.2.3.txt`.
- Upload it with the Original Name format option.
- The file will be available under `https://example.com/u/1.txt`, while `/u/1.2.3.txt` will 404.

### Version

latest (ghcr.io/diced/zipline:latest)

**Comment by diced** [comment]
Finally, someone has ran into this issue! This is happening because Zipline just splits using the delimiter `.` which causes the issue you had.

I will try considering using some utility functions within `node:path`
https://nodejs.org/api/path.html#pathparsepath


```js
path.parse('1.2.3.4.txt')
// returns 
{
  root: '',
  dir: '',
  base: '1.2.3.4.txt',
  ext: '.txt',
  name: '1.2.3.4'
}
```

**Comment by diced** [comment]
Fixed https://github.com/diced/zipline/commit/4a46f15833a11015f8d3e827d217a28d1323fa45

**Comment by FibreTTP** [comment]
@diced

This has resurfaced, filenames are truncated to the first dot. My ShareX naming format starts with the date, and thus I'm getting constant `file with the same name already exists` errors.

**Comment by diced** [comment]
> This has resurfaced, filenames are truncated to the first dot. My ShareX naming format starts with the date, and thus I'm getting constant file with the same name already exists errors.

what exactly is your filename?

**Comment by FibreTTP** [comment]
Something like `2026-04-14_14.10_CivilizationVI_DX12_yr4tLnhu.png`.

It gets truncated to `2026-04-14_14.png`.

<img width="699" height="43" alt="Image" src="https://github.com/user-attachments/assets/a6ed4045-c4dd-4778-b211-40482713d268" />

**Comment by diced** [comment]
should be fixed in that commit ^^
