### ISSUE TITLE
Bug:  "Updating user..." hang if attempting to set an avatar too large

### ISSUE THREAD

**Issue by CursedBlackCat** [dicedtomatoreal/typex#389]
### What happened?

If you attempt to set an avatar with a file size that is too large, the dashboard hangs at "Updating user..."

Steps to reproduce:
1. Go to Manage Account
2. Click the option to upload an avatar
3. Select an image with a large file size. In my case, a 2.91MB image that is 1284x1284 px was large enough to cause this issue.
4. The "Updating user..." popup will now hang, and the avatar will not be set.

In my case, compressing the image down to 694KB using TinyPNG was enough to resolve the issue, but perhaps there should be some more user-friendly indication that something has gone wrong rather than having the action hang for an extended duration of time.

### Version

latest (ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox

### Zipline Logs

```
zipline-zipline-1   | 2023-04-30 06:31:24,709 AM info  [server::response] PATCH /api/user -> 413
```

**Comment by diced** [comment]
Next.js seems to limit body size to some small number - I have tried to set it to a larger number before, though it never seemed to work.

**Comment by CursedBlackCat** [comment]
Hmm. If this isn't something that could be easily fixed, would it at least be possible to have something on Zipline's side that will reject avatar uploads that exceed whatever file size breaks Next.js, so that the user isn't left wondering what's happening when their avatar change gets stuck and doesn't work?

**Comment by diced** [comment]
Seems like they might have fixed it or something, I have raised the limit to 50mb, which is MORE than enough for profile pics.
