### ISSUE TITLE
Bug: DISCORD_UPLOAD_EMBED_IMAGE Fails

### ISSUE THREAD

**Issue by lyrx2k** [dicedtomatoreal/typex#390]
### What happened?

Yo i found out that the Image embed from the discord logs fails if you have turnd on embed on your upload settings (sharex config)..

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Zipline Logs

```shell
No logs
```

### Browser Logs

```shell
No logs
```

**Comment by diced** [comment]
I'm unsure what this is referring to, the embed when posting a link in discord or discord webhook embeds?
