### ISSUE TITLE
Bug: .env.local.example references obsolete CORE_HTTPS variable

### ISSUE THREAD

**Issue by fletchowns** [dicedtomatoreal/typex#392]
### What happened?

The .env.local.example references a variable called `CORE_HTTPS` here: https://github.com/diced/zipline/blob/4a46f15833a11015f8d3e827d217a28d1323fa45/.env.local.example

It looks like this got changed to `CORE_RETURN_HTTPS` at some point: https://github.com/diced/zipline/blob/eedeb89c7d75c951998e3571df2ca38af1d8e9ad/src/lib/config/readConfig.ts

It looks like the docker-compose.yml reference was updated: https://github.com/diced/zipline/commit/58e8c103b780f8817e1d3c0ab230f919185dcbfa

So I think the one in .env.local.example just needs to be updated to be `CORE_RETURN_HTTPS`

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Firefox

### Zipline Logs

```shell
N/A
```

### Browser Logs

```shell
N/A
```

### Additional Info

N/A

**Comment by diced** [comment]
Fixed https://github.com/diced/zipline/commit/ce26a414ac49cd1e7dc8db54af6c11a6850ff472
