### ISSUE TITLE
Bug: DATASOURCE_LOCAL_DIRECTORY doesn't accept absolute paths

### ISSUE THREAD

**Issue by fletchowns** [dicedtomatoreal/typex#393]
### What happened?

Sort of a bug but perhaps this is by design for a specific reason.

I wanted to set my `DATASOURCE_LOCAL_DIRECTORY` to be a directory outside of the folder the app resides in. For example if the source of the app is in `/usr/src/zipline` and I want to save uploads to `/var/lib/zipline`. I set `DATASOURCE_LOCAL_DIRECTORY=/var/lib/zipline` but then I got an error in my logs when uploading a file:
```
[Error: ENOENT: no such file or directory, open '/usr/src/zipline/var/lib/zipline/test_photo.jpg'] {
2023-05-03T22:47:44.829361762Z   errno: -2,
2023-05-03T22:47:44.829364599Z   code: 'ENOENT',
2023-05-03T22:47:44.829366444Z   syscall: 'open',
2023-05-03T22:47:44.829368451Z   path: '/usr/src/zipline/var/lib/zipline/test_photo.jpg'
2023-05-03T22:47:44.829370528Z }
```

It looks like `DATASOURCE_LOCAL_DIRECTORY` must always be a relative path. I think it would be more intuitive to treat it as an absolute path if the leading character is a /

As a workaround I just had to set it to a relative path:
```
DATASOURCE_LOCAL_DIRECTORY=../../../var/lib/zipline
```

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Firefox

### Zipline Logs

```shell
See above
```

### Browser Logs

```shell
N/A
```

**Comment by diced** [comment]
This is on purpose, your uploads are supposed to be in Zipline's directory.

**Comment by fletchowns** [comment]
> This is on purpose, your uploads are supposed to be in Zipline's directory.

I can see the reasoning. However, it is often the case with apps that data is stored outside of where the app lives. For example with postgres, data is typically stored in `/var/lib/postgresql` but the app itself resides in `/usr/lib/postgresql`. It's nice having this flexibility. Zipline supports it with the relative path, but it could be just a _little_ more intuitive to treat a leading / as absolute path.

**Comment by diced** [comment]
https://github.com/diced/zipline/commit/ec09458ad35cea374c05ea38f1c77072ac657514 Full paths and relative paths now work, ex. `/tmp/uploads` will work and `./uploads` will be turned into `/path/to/zipline/uploads`

**Comment by fletchowns** [comment]
Awesome! Thanks so much @diced !

**Comment by crosscutsaw** [comment]
> [ec09458](https://github.com/diced/zipline/commit/ec09458ad35cea374c05ea38f1c77072ac657514) Full paths and relative paths now work, ex. `/tmp/uploads` will work and `./uploads` will be turned into `/path/to/zipline/uploads`

hello,

i didn't wanted to open new issue since it's talked here.

when i assign `DATASOURCE_LOCAL_DIRECTORY=/tmp/test` it's end up in `/var/lib/docker`. like this:

```
find / -name Z3QcXw.ts
/var/lib/docker/overlay2/c657aa6e3b667c416d73bebe68614ac295bb5d024e09421d031a0e9aba7c8e5f/diff/tmp/test/Z3QcXw.ts
/var/lib/docker/overlay2/c657aa6e3b667c416d73bebe68614ac295bb5d024e09421d031a0e9aba7c8e5f/merged/tmp/test/Z3QcXw.ts
```

but i want files stored exactly in `/tmp/test`. am i missing something or is it how it's work?

thanks in advance,
