### ISSUE TITLE
Bug: Error when building

### ISSUE THREAD

**Issue by RappyTV** [dicedtomatoreal/typex#404]
### What happened?

when I try to run `npm run build` I get this error:
```
- info Collecting page data ..2023-05-13 01:51:13,536 PM error [config] Config is invalid, see below:
2023-05-13 01:51:13,539 PM error [config] CombinedPropertyError (1)
  Received one or more errors

  input.core
  | MissingPropertyError > core
  |   A required property is missing
```

I know it's just a stupid mistake on my behalf but I don't know how to fix it

### Version

upstream (ghcr.io/diced/zipline:trunk)

**Comment by diced** [comment]
When building from source, you will need a configuration setup with the 2 required variables. If you want to skip it run it with the environment variable `ZIPLINE_DOCKER_BUILD=1`, so `ZIPLINE_DOCKER_BUILD=1 npm run build`.

**Comment by RappyTV** [comment]
okay that worked. but when I try to run `npm run start` I get this error: 

```
> zipline@3.7.0 start
> node dist

/root/zipline/dist/index.js:1108
  switch (config_default.datasource.type) {
                         ^

TypeError: Cannot read properties of null (reading 'datasource')
    at Object.<anonymous> (/root/zipline/dist/index.js:1108:26)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.9.1
```

**Comment by TacticalTechJay** [comment]
The env variable is used only with building without a config. Do not set it when starting.

**Comment by RappyTV** [comment]
when I unset the env I get the original error again

**Comment by TacticalTechJay** [comment]
It could be that you haven't set your config with a `.env.local` from `.env.local.example` if you have the original error when starting.

**Comment by RappyTV** [comment]
yea i forgot that. now it works. thank you.
