### ISSUE TITLE
Bug: invite modal dropdown

### ISSUE THREAD

**Issue by wraithy** [dicedtomatoreal/typex#409]
### What happened?

The invite expiration dropdown gets cut off if it exceeds the modal height. 

![image](https://github.com/diced/zipline/assets/83000298/b7269f68-90b5-4f7c-8991-5fb3706a355e)

It is caused by the overflow being set to hidden on `div.zipline-ScrollArea-root zipline-1deqy7c`.

### Version

upstream (ghcr.io/diced/zipline)

**Comment by TacticalTechJay** [comment]
I can't seem to reproduce this issue in a fresh container using the same docker image that you specified. Are you sure you're this image: `ghcr.io/diced/zipline:trunk`?

**Comment by TacticalTechJay** [comment]
If you are using `ghcr.io/diced/zipline` or `ghcr.io/diced/zipline:latest` as the docker image, it may be likely that this bug is already patched in `ghcr.io/diced/zipline:trunk`.

**Comment by wraithy** [comment]
> If you are using `ghcr.io/diced/zipline` or `ghcr.io/diced/zipline:latest` as the docker image, it may be likely that this bug is already patched in `ghcr.io/diced/zipline:trunk`.

Ah yes my bad, I am indeed using `ghcr.io/diced/zipline` as the image. I am still new to using GitHub and Docker so I apologise for any mistakes or confusion haha.
