### ISSUE TITLE
Bug: Unable to run npm start

### ISSUE THREAD

**Issue by BLAMEITONBRADEN** [dicedtomatoreal/typex#412]
### What happened?

2023-05-24 12:08:53,172 AM info  [datasource] using Supabase(zipline) datasource
2023-05-24 12:08:53,195 AM info  [database::migrations] establishing database connection
2023-05-24 12:08:53,196 AM info  [database::migrations] ensuring database exists, if not creating database - may error if no permissions
2023-05-24 12:08:53,424 AM error [database::migrations] failed to push schema
2023-05-24 12:08:53,424 AM error [database::migrations] Failed to migrate database... exiting...
2023-05-24 12:08:53,425 AM error [database::migrations] Error: db error: ERROR: function gen_random_uuid() does not exist
HINT: No function matches the given name and argument types. You might need to add explicit type casts.
   0: sql_schema_connector::apply_migration::migration_step
           with step=CreateTable { table_id: TableId(0) }
             at schema-engine/connectors/sql-schema-connector/src/apply_migration.rs:21
   1: sql_schema_connector::apply_migration::apply_migration
             at schema-engine/connectors/sql-schema-connector/src/apply_migration.rs:10
   2: schema_core::state::SchemaPush
             at schema-engine/core/src/state.rs:433

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

**Comment by TacticalTechJay** [comment]
Which database did you try to use zipline with?

**Comment by BLAMEITONBRADEN** [comment]
Supabase.

**Comment by TacticalTechJay** [comment]
I... don't think that's supported as a database with zipline. It can, however, be used as a datasource.

**Comment by diced** [comment]
I'm pretty sure it should work as it is postgres, though i have not tested it.

**Comment by BLAMEITONBRADEN** [comment]
I've got it already to work. However, when uploading anything and opening it on the site, it just presents this error

{"statusCode":500,"error":"Internal Server Error","message":"stream.Readable.from Web is not a function"}

**Comment by TacticalTechJay** [comment]
What version of node are you using?

**Comment by BLAMEITONBRADEN** [comment]
I’m unsure as i’m not on my pc atm but it’s 16.2.x i believe 


Sent from Yahoo Mail for iPhone


On Thursday, May 25, 2023, 1:03 PM, Jayvin Hernandez ***@***.***> wrote:




What version of node are you using?

**Comment by TacticalTechJay** [comment]
Use at least v17 for node

**Comment by diced** [comment]
Sorry the docs are out of date, but you should be using the latest LTS version of node, currently v18. That error should be fixed once you update.
