### ISSUE TITLE
Bug: Invalid date on never expiring invites

### ISSUE THREAD

**Issue by wraithy** [dicedtomatoreal/typex#414]
### What happened?

This might be a result of the same issue from https://github.com/diced/zipline/issues/410 however I thought I would make it a separate issue just in case. 

Basically whenever I try to create an invite that never expires I get the following message.

![image](https://github.com/diced/zipline/assets/83000298/4e156645-4150-4a6b-bf63-fd856879b306)

![image](https://github.com/diced/zipline/assets/83000298/c7b83527-f4dd-4265-87ae-95f6b38d1a30)
![image](https://github.com/diced/zipline/assets/83000298/91eb965b-ee24-4e2d-a8bb-ce7ce4948fe9)

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### Zipline Logs

```shell
2023-05-29 09:51:57,428 PM info  [server::response] GET /dashboard -> 200
2023-05-29 09:52:03,640 PM info  [server::response] GET /dashboard/invites -> 200
2023-05-29 09:52:04,318 PM info  [server::response] GET /api/user -> 200
2023-05-29 09:52:04,637 PM info  [server::response] GET /api/auth/invite -> 200
2023-05-29 09:52:05,398 PM info  [server::response] GET /api/version -> 200
2023-05-29 09:52:11,619 PM info  [server::response] POST /api/auth/invite -> 400
2023-05-29 09:52:11,776 PM info  [server::response] GET /api/auth/invite -> 200
```

**Comment by diced** [comment]
I don't think it was ever intended to have a never option, a small oversight as the POST invite code disallows no expiry dates.

**Comment by wraithy** [comment]
I see, I feel like having a no expiry option would be nice since I was trying to invite my friend and by the time he tried to sign up it was expired (granted I did only set it to 3 days).

**Comment by diced** [comment]
I guess that seems fine. I'll probably add it in within a later version though as it requires a change of the database.

**Comment by wraithy** [comment]
Yea it's not a huge deal, would just be a nice addition.

**Comment by diced** [comment]
https://github.com/diced/zipline/commit/86277a091c36156d0fa95da391d1457e7ab7e219, removed never option. I'll close this issue and I would advise making a discussion about adding the never option so it stays in development.
