### ISSUE TITLE
Bug: Video preview thumbnails formatting issue

### ISSUE THREAD

**Issue by fletchowns** [dicedtomatoreal/typex#415]
### What happened?

Thanks for the [new video preview feature](https://github.com/diced/zipline/discussions/376)!

I was trying it out and ran into a small formatting issue with the thumbnails.

In Firefox 113.0.1 on Windows 11 the container is a little short:
![image](https://github.com/diced/zipline/assets/153107/61be990d-13ac-41a5-b0d3-e312d45d6446)

Chrome 113.0.5672.127 on Windows 11 has a slightly different issue:
![image](https://github.com/diced/zipline/assets/153107/cfb2edbd-b674-4f8d-8f41-661f4a6eef8f)

Appreciate your work on Zipline!

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox, Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Zipline Logs

```shell
N/A
```

### Browser Logs

```shell
N/A
```

**Comment by TacticalTechJay** [comment]
Has the latest commit fixed your problem?

**Comment by fletchowns** [comment]
Yeah looks better now, thanks @TacticalTechJay !

Though, there is a slight issue with a video I have that is square. It renders pretty tall in the grid view:
![image](https://github.com/diced/zipline/assets/153107/36efe80f-7464-4750-a7b8-0944b9dc2eca)

On the popup view you have to scroll to see the controls at the bottom of the popup:
![image](https://github.com/diced/zipline/assets/153107/36ee4f0c-6506-4a0c-861f-672707c06118)

Here's a link to the file in question: https://files.fletchowns.net/u/2015-08-03.mp4

**Comment by diced** [comment]
It's supposed to be like that, as it tries it's best to match the same resolution of the video. It could be a problem I guess with big videos...

**Comment by diced** [comment]
Will be closing.
