### ISSUE TITLE
Bug: wide avatars on Safari iOS

### ISSUE THREAD

**Issue by wraithy** [dicedtomatoreal/typex#419]
### What happened?

Avatars are ***wide*** when viewed on Safari on iOS (I assume some extra CSS needs to be added specifically for Safari).

![image](https://github.com/diced/zipline/assets/83000298/e40c1c58-3dd1-4f58-ac22-a900197ba822)

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Safari

**Comment by diced** [comment]
Should be fixed https://github.com/diced/zipline/commit/226d946ec84cc73ba8da24240953ae0a09ca6d03
