### ISSUE TITLE
Bug: /raw/ links returns HTTP 500

### ISSUE THREAD

**Issue by nekusfemboy** [dicedtomatoreal/typex#421]
### What happened?
When configured S3 Storage with MinIO `/raw/` links return HTTP 500 Error but when visiting the file directly from cdn link:
`https://s3.domain.com/uploads/file.png` and trying to open `/raw/` link again is starts to work and error disappears.

### Version
Latest (ghcr.io/diced/zipline:latest)

### Steps to reproduce
Setup S3 Storage using MinIO and create a bucket with the following bucket configuration:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::uploads"
            ]
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:PutObject",
                "s3:AbortMultipartUpload",
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:ListMultipartUploadParts"
            ],
            "Resource": [
                "arn:aws:s3:::uploads/*"
            ]
        }
    ]
}
```
And setup it in Zipline and try to upload files.

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox, Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc), Firefox Mobile

### Zipline Logs

```shell
No response
```

### Browser Logs

```shell
to load resource: the server responded with a status of 500 ()
```

**Comment by diced** [comment]
Are there any relevant Zipline logs or browser logs, other than the `to load resource: the server responded with a status of 500 ()`?

Also make sure that your access keys have the ability to access files in your bucket. You can verify this if you can view files in the normal files page within the dashboard.

**Comment by TacticalTechJay** [comment]
@nekusfemboy Do you have any more logs from Zipline and browser that could lead us in the right direction?

**Comment by diced** [comment]
Closing as stale, feel free to reopen if the problem persists.
