### ISSUE TITLE
Bug: Zipline gets rendered unusable

### ISSUE THREAD

**Issue by WinterFe** [dicedtomatoreal/typex#425]
### What happened?

Fresh install, config perfectly good.

Launch Zipline, restore a backup of images, urls, folders. Zipline works for ~5 mins then restarts, finds all videos without thumbnails, does nothing else. Shortly after, gets stuck in a restart loop, spamming the console with validating config/"Using S3 Datasource". Zipline never launches properly.

![image](https://github.com/diced/zipline/assets/42700057/d8abee9b-8256-465c-902a-964a95e19a24)
![image](https://github.com/diced/zipline/assets/42700057/7b85f4a0-ac5a-4c5e-85d7-3a9ae0c4eb20)
![image](https://github.com/diced/zipline/assets/42700057/3a28f2c3-fb30-474a-a229-b7f5b98bc94e)

NOTE: images are not in order

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Firefox, Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc), Safari, Firefox Mobile, Safari Mobile

**Comment by TacticalTechJay** [comment]
172 worker threads... dear god

**Comment by diced** [comment]
Should be fixed in https://github.com/diced/zipline/commit/4a254c55c81248235c2ed7dfdec378ebe3d6f026
