### ISSUE TITLE
Bug: flashing invite divs when no invites exist 

### ISSUE THREAD

**Issue by wraithy** [dicedtomatoreal/typex#427]
### What happened?

This is a very minor issue but I thought I would post it since it's most likely an easy fix. 

When looking at the invites page in grid view, instead of it displaying a message stating that no invites exist, it shows 3 divs which flash (acting as if the content is loading). List view shows "No records" so it is just the grid view that is experiencing issues.

![image](https://github.com/diced/zipline/assets/83000298/75a98402-440e-49db-b62c-23d7a215b07d)

Creating an invite does resolve the issue so I assume it is just an issue with displaying a message when no invites exist.

![image](https://github.com/diced/zipline/assets/83000298/fd5ca64a-8211-443c-bc10-922008ffcf8e)

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment]
Fixed in https://github.com/diced/zipline/commit/b02adca6dbf02a7142f37dad38813ad8b7c31491
