### ISSUE TITLE
Bug: Hiding non image files make them disappear

### ISSUE THREAD

**Issue by IThundxr** [dicedtomatoreal/typex#428]
### What happened?

Upload a non image file .zip, .pdf, .jar etc 
favorite it
it will disappear but will still exist just cant be seen in the ui

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment]
Fixed in https://github.com/diced/zipline/commit/3ab3202b92329e5874311b9ff29b950614382a68
