### ISSUE TITLE
Bug: Thumbnail worker crashes zipline

### ISSUE THREAD

**Issue by ItzDerock** [dicedtomatoreal/typex#444]
### What happened?

I have around 500 mp4s on my zipline instance, and after enabling `FEATURES_THUMBNAILS=true`, it started processing a few before I got the error:
![image](https://github.com/diced/zipline/assets/14848722/31ee4c3e-b1a2-4d8b-b6a5-84fce13e518f)

and if I try to restart the instance, the error is immediately thrown.
![image](https://github.com/diced/zipline/assets/14848722/918546ea-3140-4cbe-83f1-9bb2828befe6)

and with `DEBUG=zipline` set, 
![image](https://github.com/diced/zipline/assets/14848722/da994d6b-545c-40b7-aeab-8fd2f558d0d3)

### Version

upstream (ghcr.io/diced/zipline:trunk)

**Comment by diced** [comment]
i think the issue resolved it self while we were troubleshooting in Discord, but the PR above now includes more ways to see errors when ffmpeg, etc. fail to generate a thumbnail.
