### ISSUE TITLE
Bug: broken images on web panel

### ISSUE THREAD

**Issue by wraithy** [dicedtomatoreal/typex#445]
### What happened?

![image](https://github.com/diced/zipline/assets/83000298/1d5db2ed-3ba1-43da-85ac-34e62afd4aa1)

the image source is `domain.tld/r/image.png?compress=false` and when I go directly to that URL I get the following

`{"statusCode":500,"code":"ENOENT","error":"Internal Server Error","message":"ENOENT: no such file or directory, open './mimes.json'"}`

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment]
looks like I forgot to include some necessary files into the docker file, it has been fixed https://github.com/diced/zipline/commit/a60d9c58b82c0444f74d6d4a1159fcaaad9cd82f
