### ISSUE TITLE
Bug: Letters cut off in the username (visual)

### ISSUE THREAD

**Issue by PietHelzel** [dicedtomatoreal/typex#448]
### What happened?

Very minor visual bug, but letters that "go lower" like p, q or g have their bottom cut off when looking at the username in the top right.

This is what it looks like with the username being "pqg":
![Unbenannt](https://github.com/diced/zipline/assets/55491906/7e586931-6416-4711-9313-9c447db712d6)

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox, Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment]
Fixed https://github.com/diced/zipline/commit/51026209530d2bf05d40afd8c3b2fea746c93213
