### ISSUE TITLE
Bug: Template editing not updating?

### ISSUE THREAD

**Issue by lamathelama** [dicedtomatoreal/typex#470]
### What happened?

Trued to edit various pages such as the user dashboard, to remove somethings and edit the login/screen.

And so change the name of the auto generated sharex files from zipline but even after reloading my docket container and restarting it it does not update.

Yes I have F5d and such.

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment]
This is not a but and shouldn't be made as an issue. Next time you encounter something like this, create a discussion in the question category. Simply editing the files does not yield any change, you will have to rebuild the container and use the new image. I suggest using the docker-compose.dev.yml file. Please note that handling new updates may become a bit of a pain in the ass when editing things without using a fork or patches.
