### ISSUE TITLE
Bug: Cyrillic filenames isn't supported

### ISSUE THREAD

**Issue by Snyaify** [dicedtomatoreal/typex#471]
### What happened?

When I upload a file that contains Cyrillic alphabet in the name via the web interface or via sharex, the resulting files in the web interface end up with strange names.

here is screens:
[filename](https://imgur.be4free.ru/i/f5d7dd01-b0f1-48b5-8a31-e022fe7e72ef.png)
[after upload](https://imgur.be4free.ru/i/dffcd1b7-709e-46b3-ac7f-6c2b1e021580.png)

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

**Comment by diced** [comment]
oh that doesn't look good rip, I'll check out what I can do to fix this but I'm unsure

**Comment by diced** [comment]
<img width="310" alt="brave_XKQeemtqJm" src="https://github.com/diced/zipline/assets/35403473/6275f614-1803-4291-b692-f0dd452b62c3">

Fixed https://github.com/diced/zipline/commit/40fb11256f295a59603d2695b62ed001ed28ec40, tested with Japanese, Chinese, Korean, Hindi and Russian characters - in theory it should work with any non-english letters now.
