### ISSUE TITLE
Bug: Failing to fetch adjective/animal list from gfycat.

### ISSUE THREAD

**Issue by Dan-Mizu** [dicedtomatoreal/typex#478]
### What happened?

I installed Zipline using the docker compose file as a stack on my portainer service, and reverse proxied it behind cloudflare on a subdomain of mine.

When attempting to use ShareX to upload screenshots to my Zipline service, i would get this error:

```
[Error: ENOENT: no such file or directory, open 'public/adjectives.txt'] {
      
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'public/adjectives.txt'
}
```

I realized that its because I used the gfycat option for the link and it did not auto-download the adjective/animals list to my public volume. I tried to get the adjective/animal list myself to find that the gfycat page returns "no server found".

https://assets.gfycat.com/adjectives
https://assets.gfycat.com/animals

However, I was able to find them using the wayback machine.

https://web.archive.org/web/20230725063838/https://assets.gfycat.com/adjectives
https://web.archive.org/web/20230705020157/https://assets.gfycat.com/animals

I manually created the files and it worked! Sadly though, it seems to be inserting spaces in-between each adjective and animal (or maybe the zero-width thing?) leading to really wonky URLs.

Is there a fix for that? Also, do you guys pull the files from the gfycat servers? If so, maybe re-locating them to a more stable location could prevent this issue in the future.

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox

### Zipline Logs

```shell
[Error: ENOENT: no such file or directory, open 'public/adjectives.txt'] {
      
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'public/adjectives.txt'
}
```

**Comment by diced** [comment]
in the docker image it copies it from source into the public/ directory, but the provided docker-compose makes a volume for the public folder, so perhaps you might have removed the files in public or something? i might make a docs guide if this happens to anyone since it seems annoying lol

**Comment by diced** [comment]
there is now a warning https://github.com/diced/zipline/commit/4849cd8221f0d1adc8f0777796a03db7ee3f5b1b
and instructions on how to replace will be added in the docs soon
