### ISSUE TITLE
Bug: Invites set to expire in 30 mins say they'll expire in 10 months

### ISSUE THREAD

**Issue by lerndmina** [dicedtomatoreal/typex#482]
### What happened?

When creating a new invite and setting it for 30 mins, the invite says it'll expire in 10 months. Hovering over it, however, seems to show the correct expiry date.
![Gif Showing issue](https://github.com/diced/zipline/assets/10632157/42d73f8c-7394-46d2-8aed-a9ea27a2e4aa)

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox, Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Zipline Logs

```shell
I don't think the logs are needed as it looks like a UI issue.
```

### Browser Logs

```shell
*There's nothing in the browser logs*
```

**Comment by diced** [comment]
Not able to reproduce, is this issue still happening? try seeing if the issue happens on different browsers

**Comment by diced** [comment]
Closing this as stale, make a comment if this happens again with what I said in the previous comment and we will reopen this.

**Comment by iiTranquility** [comment]
Sorry to open this again, having the same issue atm.

In this screenshot it shows Expired NaN years ago, but they've just been created as 7 day invites.

Happening on Vivaldi, Chrome and Firefox.

https://i.iitranq.co.uk/u7PzcLQYy0.png


Not sure what other info you need, please lmk :)

**Comment by iiTranquility** [comment]
I had the same issue on 3.7.3/4 I believe also.

https://i.iitranq.co.uk/Y1EU707LMw.png

Is a screenshot of the issue taken on the 2nd October, and I all did was create an invite, nothing else has changed apart from updating Zipline.
