### ISSUE TITLE
Bug: Discord embed breaks any other embed

### ISSUE THREAD

**Issue by ItsMelodyy0102** [dicedtomatoreal/typex#485]
### What happened?

When using the "Embed" setting in generating ShareX configs, it'll embed on discord. However if you then try embedding it in, for example, a phpbb forum, using the [img] tags, the image won't embed. The only workaround, currently, is to turn embeds off in ShareX so it doesn't use Discord's embed model and then embedding it in phpbb. 

Showing: https://cdn.vndctr.nl/u/2023-11-10_21:59:02.png
Expected: https://cdn.vndctr.nl/u/2023-11-10_22:01:44.png

EDIT: It's also doing the same thing on IP.Board. Not embedding the image itself but instead displaying it as a link, rather than embedding, which is the expected behavior

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox

**Comment by diced** [comment]
I don't think there is much I can do to fix this, but a workaround is just using the raw link, `https://example.com/r/<filename>.abc`, which provides a raw link to the file and hopefully those forum sites work with that. Unfortunately if they don't support og image tags and whatnot I can't do anything else.

**Comment by ItsMelodyy0102** [comment]
> I don't think there is much I can do to fix this, but a workaround is just using the raw link, `https://example.com/r/<filename>.abc`, which provides a raw link to the file and hopefully those forum sites work with that. Unfortunately if they don't support og image tags and whatnot I can't do anything else.

That actually was exactly what I needed. Thank you!
