### ISSUE TITLE
Bug: (API) Create a Invite

### ISSUE THREAD

**Issue by sinnafuls** [dicedtomatoreal/typex#488]
### What happened?

Following the API docs for creating an Invite, however i get Invalid date error 400 every time.

![image](https://github.com/diced/zipline/assets/92541374/cecae0ff-e390-4718-8bef-f12f3d95446b)
![image](https://github.com/diced/zipline/assets/92541374/0688d106-b355-48bf-8989-c0ce974070d1)

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

**Comment by diced** [comment]
Invites need an expiration date (this will be "fixed" in v4, so you can have invites that don't expire, etc.), You can put something like `30m` to make it choose a date 30 minutes from now, or if you want a specific date `date=<js resolvable date` instead. You can check if it resolves correctly by doing `Date("your input")` in a browser console or `node`.

**Comment by sinnafuls** [comment]
> Invites need an expiration date (this will be "fixed" in v4, so you can have invites that don't expire, etc.), You can put something like `30m` to make it choose a date 30 minutes from now, or if you want a specific date `date=<js resolvable date` instead. You can check if it resolves correctly by doing `Date("your input")` in a browser console or `node`.

I tried setting an expiration date in the example above and it didn't work?
