### ISSUE TITLE
Bug: thumbnails not aligned to the middle

### ISSUE THREAD

**Issue by wraithy** [dicedtomatoreal/typex#503]
### What happened?

The thumbnails generated by Zipline are not aligned to the middle like the other images shown on the files page. I managed to fix it using Cloudflare apps with the following CSS...

```
.zipline-1phlsj0 {
    display: flex !important;
    align-items: center !important;
    justify-content: center !important;
}
```

### Version

upstream (ghcr.io/diced/zipline:trunk)

**Comment by diced** [comment]
fixed https://github.com/diced/zipline/commit/abb5bb5f25d066a01710b01a7146749a366ea38d
