### ISSUE TITLE
Bug: url shorten

### ISSUE THREAD

**Issue by catingdev** [dicedtomatoreal/typex#508]
### What happened?

0|cdn  | 2023-12-09 02:27:56,419 PM info  [shorten] User admin (1) shortenned a url https://google.com/ (p8ezLa)
0|cdn  | TypeError: Cannot read properties of undefined (reading 'url')
0|cdn  |     at Object.postUrl (/root/zipline/dist/index.js:1379:43)
0|cdn  |     at Object.urlsRoute (/root/zipline/dist/index.js:1671:9)

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

**Comment by diced** [comment]
I'm gonna need more information here like your config and what options you used when shortening.

**Comment by diced** [comment]
Closed as stale, feel free to reopen if the issue persists!
