### ISSUE TITLE
Bug: `/api/upload` always returns 200

### ISSUE THREAD

**Issue by RappyTV** [dicedtomatoreal/typex#512]
### What happened?

The route always returns 200 and puts the real status code in the body. I would really appreciate if you could return the real status code and also if you'd capitalize the error messages :)

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

**Comment by diced** [comment]
Seems fine to me, here are some examples: (putting in values that will cause a non OK status)
![image](https://github.com/diced/zipline/assets/35403473/b4a14d0a-7ffd-410c-bbb0-4ab9e82bd8e5)
![image](https://github.com/diced/zipline/assets/35403473/a0d6deef-f842-4c6e-a13c-f6538826a6fe)

**Comment by RappyTV** [comment]
hmm weird, some days ago i had a 200 status code but a 400 code in the body, I unfortunately don't have a screenshot. but it's fine because it works now. but what about the lowercase errors? I use the api for a custom uploader and it just does not look pretty when the error messages are not capitalized.

**Comment by diced** [comment]
i don't really care if it looks pretty or not, its not a priority lol
