### ISSUE TITLE
Bug: Images get stretched in a weird way

### ISSUE THREAD

**Issue by maximmax42** [dicedtomatoreal/typex#527]
### What happened?

The image viewer stretches images sometimes. My screen resolution is 1080p, Chrome's viewport is 1920x919.

### Input (1920x1920)
![square-glitch-golden-3840x3840-460](https://github.com/diced/zipline/assets/2225711/7a5f75a3-52c8-4603-affa-b729a8ef08e8)
### Output
![image](https://github.com/diced/zipline/assets/2225711/4deb4ced-003d-46d7-b5ba-50b73be38b8f)
### Input (1080x1080)
![test2](https://github.com/diced/zipline/assets/2225711/bb63a246-b996-49ec-a7b3-d6fce2deb488)
### Output
![image](https://github.com/diced/zipline/assets/2225711/bfa1e987-496c-4044-ba8a-adb92d64534d)
### Input (1080x1920)
![test](https://github.com/diced/zipline/assets/2225711/bea78cda-d93e-4946-a447-1db73374c379)
### Output
![image](https://github.com/diced/zipline/assets/2225711/3eb5496b-1862-41b3-b414-42079554c102)
### Input (2160x3840)
![test3](https://github.com/diced/zipline/assets/2225711/4101a8fe-ac3c-493f-afcd-45262239febd)
### Output
![image](https://github.com/diced/zipline/assets/2225711/ccf3304a-0c04-46cc-945c-c06b5612bf26)

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment]
By the looks of it, sometimes it seems to be fine and then sometimes it's being stretched/shrinked?

**Comment by maximmax42** [comment]
Yeah, pretty much. I can't see any rhyme or reason though.

**Comment by diced** [comment]
should be fied https://github.com/diced/zipline/commit/f3634eff48ea72cbf6335e718af9a88635286a1c

**Comment by maximmax42** [comment]
It doesn't distort now, but big images don't fit the viewport now causing scroll bars to appear.

**Comment by diced** [comment]
i was able to get shrinking working with big images, but not with small (i thought this would be a fine trade off since i couldn't find out a way to make it work both ways).

Could you tell me what the image width and height was, I'll give it a try on my end.

**Comment by maximmax42** [comment]
Interesting, I just checked my test images on phone, and unlike on pc everything displays correctly.

https://stash.maximmax42.ru/naSAf.jpg
https://stash.maximmax42.ru/0gbjn.jpg
https://stash.maximmax42.ru/baPsL.jpg
https://stash.maximmax42.ru/bCY1f.jpg
Here are my 4 testing images, all are displayed with scroll bars on my 1080p monitor.

Now that I think about it, I didn't try to do force reload the viewing page after updating Zipline, maybe something from the old version remained. I'll test it later.

**Comment by maximmax42** [comment]
> Here are my 4 testing images, all are displayed with scroll bars on my 1080p monitor.

Correction: top link (1080x1920) shows up fine, rest have scroll bars.

> I didn't try to do force reload the viewing page after updating Zipline, maybe something from the old version remained. 

I tried. There definitely was some leftover stuff in cache, but it only fixed one image (see above).

**Comment by diced** [comment]
> > Here are my 4 testing images, all are displayed with scroll bars on my 1080p monitor.
> 
> Correction: top link (1080x1920) shows up fine, rest have scroll bars.
> 
> > I didn't try to do force reload the viewing page after updating Zipline, maybe something from the old version remained.
> 
> I tried. There definitely was some leftover stuff in cache, but it only fixed one image (see above).

Tested these on my end, 2560x1440 monitor, top and bottom link seem to work (once the image is fully loaded it seems to conform to the viewport), but the middle two links seem to have a vertical scrollbar... no idea why this is happening lol, ill still try out different stuff

**Comment by diced** [comment]
I think it's fixed here https://github.com/diced/zipline/commit/5b88b597243429d883df70d5ffddf2f474f4a994, I tried it on your images and it seems to be resizing just fine!

**Comment by maximmax42** [comment]
Yup, seems to work on my end as well.
