### ISSUE TITLE
Bug: Can download that don't exist in DB but on filesystem

### ISSUE THREAD

**Issue by IceToast** [dicedtomatoreal/typex#531]
### What happened?

*A bug happened!*

I'm still able to download a file that is not present in the db (either by a bug or manual db deletion) but still exist in the datasource (e.g. local storage).

Seems like this might be unwanted:
![image](https://github.com/diced/zipline/assets/54889359/aeb43b17-5a1b-416e-b9a5-9d3d44c63cd7)

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

**Comment by diced** [comment]
Not a bug, but a feature.
