### ISSUE TITLE
Bug: {unknown_modifier} showing even though {file.size::bytes} is a valid modifier

### ISSUE THREAD

**Issue by iiTranquility** [dicedtomatoreal/typex#532]
### What happened?

Hi!

Currently using Zipline on Portainer, version latest 3.7.8 and currently the file size bytes modifier is showing as unknown when embedding via the Discord webhook.
The embed when posting the link, shows the correct filesize in bytes.

This behaviour isn't present on 3.7.5, but is present on versions afterwards.

![Discord_QrAviX4RA6](https://github.com/diced/zipline/assets/21291440/ae2fb035-d5c2-414f-a2c7-d83ca570c4aa)

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Zipline Logs

```shell
It just shows the unknown modifier in logs.
so much data to go through.
```

**Comment by diced** [comment]
should be fixewd in https://github.com/diced/zipline/commit/23ef407dd322add1ddcdbda7d5a81dfd4c6e79f7
