### ISSUE TITLE
Feature request: Timezone variables

### ISSUE THREAD

**Issue by iiTranquility** [dicedtomatoreal/typex#533]
### What happened?

Diced told me to make a GitHub issue regarding timezone variables.

![image](https://github.com/diced/zipline/assets/21291440/1d205129-2948-4adf-bfa8-bca28c8e90f3)

As per diced in Discord, this should have been added around Christmas time but shit happens

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### Zipline Logs

```shell
n/a
```

### Browser Logs

```shell
n/a
```

### Additional Info

n/a

**Comment by diced** [comment]
Already exists in v3.7.8
