### ISSUE TITLE
Bug: 404 Error Makes A 200 Status Code & Embed Views Per File

### ISSUE THREAD

**Issue by L7NEG** [dicedtomatoreal/typex#534]
### What happened?

When Setting URLS_ROUTE and UPLOADER_ROUTE to / the 404 wont work it just tells the server that it is a status code 200 
![Screenshot 2024-02-03 194756](https://github.com/diced/zipline/assets/88356593/a668b284-e10c-4627-a468-4cd4899eb113)
![Screenshot 2024-02-03 194805](https://github.com/diced/zipline/assets/88356593/4e133bd3-c70f-4ff0-93bd-c9eaa0c3f1d4)
Like It Works For What After The First slash ex https://e-z.ftp.sh/hhhh/wwiwiw
![image](https://github.com/diced/zipline/assets/88356593/3be7103e-e653-40b0-989c-6d6e73bc44f0)

But Not With https://e-z.ftp.sh/hhhh
![image](https://github.com/diced/zipline/assets/88356593/0c8cb6e7-91af-45e8-9e09-02c22461e079)
![Screenshot_2024-02-03_042203](https://github.com/diced/zipline/assets/88356593/3c635713-a1c2-4378-9ce0-e1ae55226044)

and for the Embed Views Per File I Mean When i turn Off Embedded The Views For It Works FIne 
![Screenshot_2024-02-03_003429](https://github.com/diced/zipline/assets/88356593/60e10850-2010-48b7-83b0-2c06d9cfa548)
![Screenshot_2024-02-03_003515](https://github.com/diced/zipline/assets/88356593/e883272d-020d-4604-8710-bb62f4586e37)

But If I Toggle It On It Wont Work It Just hows The Views To 0
![Screenshot_2024-02-03_003527](https://github.com/diced/zipline/assets/88356593/1e81940b-6f73-46d0-8dd3-b00b64f043d9)
![Screenshot_2024-02-03_003607](https://github.com/diced/zipline/assets/88356593/e4f17b6f-f4a0-4939-ab2b-0765271d83ea)
![Screenshot_2024-02-03_003623](https://github.com/diced/zipline/assets/88356593/bbb0312a-7f42-4ad3-8602-0b27c2d96e1b)

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

all chromium and firefox based

**Comment by L7NEG** [comment]
What browser(s) are you seeing the problem on?
all chromium and firefox based

**Comment by diced** [comment]
the logs are a lie and just say 200 - if you check network logs in developer tools you should see a 404 status code. This is going away in v4 anyway.
