### ISSUE TITLE
Bug: Filenames with # don't work

### ISSUE THREAD

**Issue by ari-party** [dicedtomatoreal/typex#535]
### What happened?

I imported my existing files from ShareX, some of which having a `#` in the beginning (e.g. screenshotting Discord) and `/u/#filename.png` is seen as a query

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment]
Not sure if there is any way to fix that, it's a browser thing that I have no control over unfortunately. If you do know a way to circumvent this then lmk.

**Comment by ari-party** [comment]
> Not sure if there is any way to fix that, it's a browser thing that I have no control over unfortunately. If you do know a way to circumvent this then lmk.

Get the **full url**. Split at /u/ or whatever and the last part is the file name.
