### ISSUE TITLE
Bug: Can't download archives

### ISSUE THREAD

**Issue by respektive** [dicedtomatoreal/typex#536]
### What happened?

Tested on rar, zip and gz files. Works fine on Chromium, but in Firefox I'm getting an error. The logs don't show anything useful. I'm not even seeing the request to the file in them, while I see other requests.
![](https://pek.li/RsRKQM.png)

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox

**Comment by diced** [comment]
Not able to reproduce this, I just tried this on a 7z, zip, tar, tar.gz, zip and they all seem to work. The problem might be with the files you are uploading, but I don't have a way of really fixing this since it is most likely a firefox issue.

**Comment by respektive** [comment]
Turns out i had some malformed nginx config that resulted in the `Content-Disposition` header being present twice for certain archive files (some weird issues i had with the file upload server i was using before). Chromium apparently just doesn't care about that, but firefox completely blocks the request then, probably some security settings that are on by default. I should have probably checked the nginx config before opening an issue, oops :see_no_evil:

**Comment by diced** [comment]
> Turns out i had some malformed nginx config that resulted in the `Content-Disposition` header being present twice for certain archive files (some weird issues i had with the file upload server i was using before). Chromium apparently just doesn't care about that, but firefox completely blocks the request then, probably some security settings that are on by default. I should have probably checked the nginx config before opening an issue, oops 🙈

No problem, glad it's fixed though!
