### ISSUE TITLE
Bug: Outdated dependency prevents building on windows

### ISSUE THREAD

**Issue by Pumpline** [dicedtomatoreal/typex#538]
### What happened?

Sharp dependency wasn't able to build on my windows server because the dependency is outdated. There was some error happening on an old version, it's simply fixed by updating the dependency to the newest version (sharp).

Error:

  nothing.vcxproj -> C:\Users\Administrator\Desktop\zipline\node_modules\sharp\build\Release\\nothing.lib
  VConnection.cpp
C:\Users\Administrator\Desktop\zipline\node_modules\sharp\src\libvips\cplusplus\VConnection.cpp(35,10): error C1083: Datei (Include) kann nicht ge”ffnet werden: "vips/vips8": No such file or directory [C:\Users\Administrator\Desktop\zipline\node_modules\sharp\build\libvips-cpp.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (C:\Users\Administrator\Desktop\zipline\node_modules\node-gyp\lib\build.js:209:23)
gyp ERR! stack at ChildProcess.emit (node:events:518:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\Desktop\\zipline\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\Desktop\zipline\node_modules\sharp
gyp ERR! node -v v20.11.1
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok 

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

**Comment by diced** [comment]
Not sure if just the version is the issue (I can update it later), but have you considered trying docker - you are less likely to run into any sorts of problems there

**Comment by TacticalTechJay** [comment]
Using npm is strongly discouraged and would recommend using yarn instead.

**Comment by diced** [comment]
@Pumpline were you able to fix the issue with yarn, it usually fixes 99% of issues like these (like jay above said). I'll be closing this since we do get similar issues like this, and npm is something we don't use around here. Feel free to reopen if the issue persists on yarn.

**Comment by Pumpline** [comment]
Hey there, this bug occured while using yarn, I've managed to fix it by updating the dependency version.
