### ISSUE TITLE
Bug: Missing favicon in webpage

### ISSUE THREAD

**Issue by arpanghosh8453** [dicedtomatoreal/typex#539]
### What happened?

I have noticed there is no default or custom favicon on the website. Is there any quick way to fix it?

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

**Comment by diced** [comment]
If you add a `public/favicon.ico` file it will work automatically. if you were using the docker compose file it should have made a volume for it with the default favicon, but it depends on how you set it up.

**Comment by arpanghosh8453** [comment]
Thank you @diced so much for the information, I had a bind mount to that folder and as soon as I added the ico file there and restarted the container, it was updated in the tab. 

Thank you so much for your quick response. The missing favicon was bothering me, given the UI is so polished. This is an amazing piece of software and does everything I need under the same hood. 

Thanks again, I am closing the issue.

**Comment by mptpro** [comment]
> favicon.ico



> and as soon as I added the ico file there and restarted the container, it was updated in the tab.

May I ask where you got the actual ico file for Zipline?  Thanks

**Comment by wraithy** [comment]
> > favicon.ico
> 
> 
> 
> 
> 
> 
> 
> > and as soon as I added the ico file there and restarted the container, it was updated in the tab.
> 
> 
> 
> May I ask where you got the actual ico file for Zipline?  Thanks

The favicon.ico file should be in your Zipline directory in the public folder.

**Comment by mptpro** [comment]
The favicon.ico file should be in your Zipline directory in the public folder.

Thanks. My public folder was empty, but I found a suitable replacement online here: https://selfh.st/icons/
