### ISSUE TITLE
Bug: IO Error when uploading a larger zip file

### ISSUE THREAD

**Issue by Pumpline** [dicedtomatoreal/typex#544]
### What happened?

When uploading a larger zip (in this case 6 gigabyte) file, an error occurs.

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox

### Zipline Logs

```shell
[Error: ENOENT: no such file or directory, open 'C:\Users\ADMINI~1\AppData\Local\Temp\2\zipline\zipline_partial_Uv2c_0_20971520'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\zipline\\zipline_partial_Uv2c_0_20971520'
}
```

### Browser Logs

```shell
Browser is not noticing this issue as I saw, tries to continue to upload but the upload bar stays stuck.
```

**Comment by diced** [comment]
Is this issue still happening? Could you turn on the [debug logs](https://zipline.diced.sh/docs/guides/debugging#enabling-debug-logs) and show the logs surrounding the error if it's still happening?

**Comment by diced** [comment]
A possibility is that the temp directory isn't being created, I don't test Zipline on windows but try to create the `C:\Users\ADMINI~1\AppData\Local\Temp\2\zipline` directory your self and see if the issue is resolved. Obviously this isn't a solution but I'll have to investigate it in more detail later on windows.

**Comment by Pumpline** [comment]
Hey there,
the named folder already exists.
https://pumpline.de/cloud/aiv314TzUFoPipftwKuh.png

**Comment by diced** [comment]
Not sure if this will fix it, but try setting the `CORE_TEMP_DIRECTORY` variable to somewhere other than inside of `AppData\Local\Temp` for example maybe just your user folder and call the directory something like zipline_temp.

reference: https://zipline.diced.sh/docs/config/core#core_temp_directory

**Comment by diced** [comment]
closing as stale
