### ISSUE TITLE
Bug: Failed to Compile

### ISSUE THREAD

**Issue by MauriceX24** [dicedtomatoreal/typex#546]
### What happened?

After I did `npm run build` (v3.7.9) it responds after some progresses an error:

```js
Failed to compile.
./src/components/Layout.tsx


419:45  Error: Delete `⏎······················`  prettier/prettier
421:1  Error: Delete `··`  prettier/prettier
422:1  Error: Del...
```

My current server:
1 Core server with 4GB and 75GB Stoarge (Ubuntu 22.04)

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### Zipline Logs

```shell
> zipline@3.7.9 build:next
> next build

   ▲ Next.js 14.1.4
   - Environments: .env.local


Failed to compile.

./src/components/Layout.tsx
419:45  Error: Delete `⏎······················`  prettier/prettier
421:1  Error: Delete `··`  prettier/prettier
422:1  Error: Delete `··`  prettier/prettier
423:1  Error: Delete `··`  prettier/prettier
428:31  Error: Delete `⏎························`  prettier/prettier
430:1  Error: Delete `··`  prettier/prettier
431:1  Error: Delete `··`  prettier/prettier
432:1  Error: Delete `··`  prettier/prettier
445:45  Error: Delete `⏎······················`  prettier/prettier
447:1  Error: Delete `··`  prettier/prettier
448:1  Error: Delete `··`  prettier/prettier
449:1  Error: Delete `··`  prettier/prettier

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
Linting and checking validity of types  .ERROR: "build:next" exited with 1.
```

**Comment by diced** [comment]
Unable to reproduce, if you made any changes make sure they fit the prettier guidelines, usually running `yarn lint --fix` will fix most of the errors. If you didn't change anything then try running the build script with yarn instead of npm, sometimes using npm with Zipline messes stuff up (i don't know why lol).

**Comment by MauriceX24** [comment]
Okay thank you :) got it somehow. Its something new for me (never worked with docker, yarn, etc... and I have this migration error which already exist. You told something to delete `XYZ_pg_data` which I currently looking for ^^

Edit: April 04.
Still didnt got it

**Comment by MauriceX24** [comment]
![putty_VWsXRltUTF](https://github.com/diced/zipline/assets/35397688/889b4914-8c33-461c-bc40-a3ea035d576b)
I reinstalled everything again, and now after `sudo yarn install` this happens. Errorlog shows me something I cant work with. (Same as in picture)

**Comment by diced** [comment]
You shouldn't be running `yarn` with `sudo`, if you happen to get permission errors your install is messed up and you should fix that first. Second, you should try to delete the `node_modules/`, `.next/` directories and run the `yarn install` command again. Make sure you are on node v18+. From the looks of it it seems like prisma isn't getting the binaries correctly, which makes me think you're running some sort of architecture that prisma doens't have prebuilt binaries for? Please provide that information in your next comment too (you can get it by running: `uname -m`, common values would be `x86_64` or `aarch64`).

>  You told something to delete XYZ_pg_data which I currently looking for ^^

im not sure what this is about, you need to provide the error Zipline shows for me to get a better grasp.

**Comment by MauriceX24** [comment]
Hey, first: thank you so much for your time :)
To your question, I use `x86_64`. Meanwhile I reinstalled everything again and did a video, where I literally did everything I did before. But since I start recording, everything above got solved. Now it stucks at the `Unable to connect to database` like in #507
 
![opera_3Vqq3XbPAL](https://github.com/diced/zipline/assets/35397688/740e6a60-0296-4d86-a73e-f34552eb629d)

I am not sure about this, since everything is default. Sorry, its my first time doing this 😅

**Comment by diced** [comment]
Did you change the database url in your .env file?

**Comment by MauriceX24** [comment]
Noup, I just changed the "changethis" variable

**Comment by diced** [comment]
well like the docs say, both the secret and database url variables need to be changed. and in the case of the database url you need to have a postgresql server running (if that wasn't obvious)

**Comment by MauriceX24** [comment]
Ohh alright, now I see.
Yep, ofc it works now - thank you so much <3
