### ISSUE TITLE
Bug: Expired photos not working as expected.

### ISSUE THREAD

**Issue by chrgeorgeson** [dicedtomatoreal/typex#556]
### What happened?

**Summary:**

When uploading files to ZipLine (3.7.9) , I set a default 2-week expiration on them. Once the expiration date is reached, the image itself is deleted, but the file metadata remains visible in the Files view. This behavior necessitates additional manual cleanup, which undermines the convenience of the expiration feature.

**Steps to Reproduce:**

1. Upload an image to ZipLine with a 2-week expiration setting.
2. Wait until the expiration date passes.
3. Observe that the image is deleted, but the file metadata still appears in the Files view.

**Observed Behavior:**

- The file metadata (name, type, size, etc.) remains in the Files view after the image is deleted.
- Clicking on the file name to open the modal reveals that the image is indeed deleted. **_Closing the modal then removes the file metadata from the Files view._**
- This results in two inconvenient options:

    1. Set expiration dates and manually clean up each file name by either deleting the stub info or viewing the file to trigger the metadata removal.
    2. Avoid using the expiration feature and manually delete the files after 2 weeks.

**Expected Behavior:**

Once the expiration date is reached, both the image and its metadata should be automatically removed from the Files view without requiring manual intervention.

**Attachments:**

1. Screenshot showing the file metadata remaining after the image is deleted
![r7kufU](https://github.com/diced/zipline/assets/31230280/3fa7d743-22e4-4523-9736-eace0f84b5da)

2. Screenshot of the Files view with multiple files where metadata should be removed
![JURD8Y](https://github.com/diced/zipline/assets/31230280/999c8303-749e-411d-a7ea-04781d4f903e)

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox, Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment]
This is expected behavior so far, the file should delete it self after the link gets accessed again. I know this seems kind of dumb but that's the way I originally implemented it. This is changing in v4 though, expired files will get deleted on an interval.

If the file is still not getting deleted after it's link has been accessed then feel free to reopen the issue :)
