### ISSUE TITLE
Bug: Thumbnails don't show up in folder view

### ISSUE THREAD

**Issue by Korgen1** [dicedtomatoreal/typex#563]
### What happened?

Steps:

Have thumbnails enabled
Create a folder
Upload video to folder
Thumbnails will show up in files but not when in a folder

![image](https://github.com/diced/zipline/assets/65197237/3462d95e-1f46-4034-b07c-c49a3a9002e0)

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment]
fixed in https://github.com/diced/zipline/commit/1f00dd51f96a58c8a02584d287041a51e5bc5c35
