### ISSUE TITLE
Bug: ShareX profile domain override forces http

### ISSUE THREAD

**Issue by NotAkitake** [dicedtomatoreal/typex#566]
### What happened?

Using the domain name override during the ShareX profile creation makes final links use http instead of https, even if you define `https://somehost.xyz` as an override.

I instead simply opted to set the domain name in `Domains` under `Manage User` and not define any override in the ShareX profile.
But I believe if this is intended, the user should be told overrides won't work with https.

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

**Comment by diced** [comment]
probably don't have this option on https://zipline.diced.sh/docs/config/core#core_return_https

**Comment by liechtenberg** [comment]
> probably don't have this option on https://zipline.diced.sh/docs/config/core#core_return_https

i was struggling with this myself too until i found this issue. perhaps document the ssl part better?
