### ISSUE TITLE
Bug: views not being counted when image is uploaded with embeds enabled

### ISSUE THREAD

**Issue by liechtenberg** [dicedtomatoreal/typex#572]
### What happened?

When generating the ShareX config with embeds enabled, the views don't seem to be getting counted. When turned off and uploading an image, the behavior is as expected.

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment]
looks like i just forgot to increment views, it's now fixed in https://github.com/diced/zipline/commit/4330bdcc4c38eef690ca441b828d1ac42c085dc0

**Comment by liechtenberg** [comment]
thanks!

**Comment by L7NEG** [comment]
W fr
