### ISSUE TITLE
Bug: files with max views and a password aren't deleted when max views is reached/exceeded

### ISSUE THREAD

**Issue by Stef-00012** [dicedtomatoreal/typex#584]
### What happened?

When uploading a file with both max views and a password, the max views is ignored

- Upload a file with max views and a password
- Open it enough times to exceed the max views
- It doesn't get deleted
It should be deleted 

https://github.com/user-attachments/assets/e8729a01-485c-4c5a-bc21-bc7ef8d1520d

### Version

upstream (ghcr.io/diced/zipline:trunk)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Additional Info

Both Zipline logs and browser logs have no error

Zipline with debug on has just the HTTP requests (403 before i put the password and 200 after)
Chrome logs just the 403 error before i put the password

**Comment by diced** [comment]
fixed https://github.com/diced/zipline/commit/f3638f3d6da6cc2aef1bf7a1656f14600d6c5a8c
