### ISSUE TITLE
Bug: V4: App Title/Zipline text in dashboard is not symetric/scneter

### ISSUE THREAD

**Issue by oie1** [dicedtomatoreal/typex#589]
### What happened?

![image](https://github.com/user-attachments/assets/c7378a7b-ccaa-473d-8299-af472b1f83fc)

### Version

other (provide version in additional info)

### Additional Info

v4

**Comment by diced** [comment]
![image](https://github.com/user-attachments/assets/0c9f0b96-583a-4e6d-b9ea-a6107f686a6d)

Technically it is centered (if it looks weird, go complain to the font and not me), and it honestly looks fine to me.
![image](https://github.com/user-attachments/assets/54d52ab3-573d-48db-bf16-76195d19ea27)
