### ISSUE TITLE
V4 Bug: Auth header wrong using Sharex config

### ISSUE THREAD

**Issue by iiTranquility** [dicedtomatoreal/typex#592]
### What happened?

I have a new instance of V4 set up, and when I generated a sharex config, the auth header was authentication instead of authorization as it is in the code.

Changing it to authorization FROM authentication makes it work.

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### Zipline Logs

```shell
N/A
```

### Browser Logs

```shell
N/A
```

### Additional Info

N/A

**Comment by diced** [comment]
I think you meant changing it from `authentication` to `authorization` worked, anyway I just accidently set the header name in the sharex generator to be `authentication` instead of `authorization`

fixed in ba3aaf6bb2d00c451b0be341615893a8b355e6cf
