### ISSUE TITLE
V4 Bug: Refreshing token gives me an error

### ISSUE THREAD

**Issue by iiTranquility** [dicedtomatoreal/typex#595]
### What happened?

When refreshing my token, I get an error only in the browser

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Browser Logs

```shell
https://chibi.iitranq.co.uk/nK5HkV0DX8Bn.png

{
    "statusCode": 400,
    "code": "FST_ERR_CTP_EMPTY_JSON_BODY",
    "error": "Bad Request",
    "message": "Body cannot be empty when content-type is set to 'application/json'"
}
```

**Comment by diced** [comment]
fixed in https://github.com/diced/zipline/commit/90de25b7219f5eb23c9310e52dcc7bf8529512aa!
