### ISSUE TITLE
V4 Bug: Avatar missing Portainer/Docker install

### ISSUE THREAD

**Issue by iiTranquility** [dicedtomatoreal/typex#596]
### What happened?

When visiting any page with an avatar, I get a 404 error to say it's missing.

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### Browser Logs

```shell
{"statusCode":404,"error":"Not Found","message":"Not Found"}
```

**Comment by diced** [comment]
I'm not able to recreate this. I'm not sure I understood what the issue is though, it might be helpful if you could run a screen recording of you doing this on a new instance.

**Comment by diced** [comment]
Discussed in discord, seemed like the issue was /api/user/avatar was giving a 404 response when there is no avatar - which is intended behavior anyway.
