### ISSUE TITLE
Bug: API stats amount=1 still shows all stats

### ISSUE THREAD

**Issue by sahara101** [dicedtomatoreal/typex#600]
### What happened?

Hello, 

even if using amount=1 I still get too many API responses. instead of just 1 (preferably the last updated one?)

Thanks!

### Version

other (provide version in additional info)

### Additional Info

Zipline V4

**Comment by diced** [comment]
Intended behavior, the stats update on an interval so you will have to wait for it to update.

**Comment by sahara101** [comment]
I still get many responses. What should amount=1 do? Maybe I’m misunderstanding the option.
