### ISSUE TITLE
Bug: Authentik Refresh Token

### ISSUE THREAD

**Issue by Aetherinox** [dicedtomatoreal/typex#602]
### What happened?

Hey. I was finally able to get v4 working after much messing around with the env vars.

V4 looks great, but the only issue I've noticed is that I attempted to integrate Authentik and Zipline together.

As soon as authentication occurs, it returns the error:
![1sSnVYkX5Z](https://github.com/user-attachments/assets/fbde81a3-2d04-4734-8d4d-ccea56b4ce6a)

<br />

I searched around and I couldn't find the code within your repository, but Authentik added a note to their documentation; available at https://docs.goauthentik.io/docs/providers/oauth2/#grant-types.

> [!NOTE]
> Starting with authentik 2024.2, applications only receive an access token. To receive a refresh token, both applications and authentik must be configured to request the offline_access scope. In authentik this can be done by selecting the offline_access Scope mapping in the provider settings.

<br />

I granted permission on my end for `offline_access`, however, the error is still thrown every time I attempt to authenticate.

![UWe45usq98](https://github.com/user-attachments/assets/ccc26803-4de5-4d8d-950b-bd835fc50032)

In the PR which adds Authentik, I noticed the section `&response_type=code&scope=openid+email+profile`

```ts
export const authentik_auth = {
  oauth_url: (clientId: string, origin: string, authorize_url: string, state?: string) =>
    `${authorize_url}?client_id=${clientId}&redirect_uri=${encodeURIComponent(
      `${origin}/api/auth/oauth/authentik`
    )}&response_type=code&scope=openid+email+profile${state ? `&state=${state}` : ''}`,
  oauth_user: async (access_token: string, user_info_url: string) => {
    const res = await fetch(user_info_url, {
      headers: {
        Authorization: `Bearer ${access_token}`,
      },
    });
    if (!res.ok) return null;

    return res.json();
  },
};
```

### Version

other (provide version in additional info)

### What browser(s) are you seeing the problem on?

Firefox, Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Zipline Logs

```shell
N/A
```

### Browser Logs

```shell
N/A
```

### Additional Info

Running:
- Zipline v4 (latest)
- Authentik 2024.6.4

**Comment by diced** [comment]
It looks like it needs the refresh_token grant type. I'll take a look into this later to see what I can do.

**Comment by Aetherinox** [comment]
Appreciate it.

**Comment by sahara101** [comment]
Thank you, I also posted this issue on discord.

**Comment by diced** [comment]
> It looks like it needs the refresh_token grant type.

Sorry, was wrong about this. It just needs the `offline_access` scope added.

Unfortunately I'm unable to test this (my authentik setup is being really weird, and i don't want to troubleshoot it right now :/), so I'm asking both of you to try out the following commit and see if the issue is fixed.

https://github.com/diced/zipline/commit/708b13000277403236429c4335508270dbaeff75

**Comment by Aetherinox** [comment]
Appreciate it. I'll update and try it out and report back.

<br />

---

<br />

### Edit
In short, yes, I can now use Authentik. Appreciate it. There's a few things to note (or if you want a new ticket):


### Cannot Unlink Authentik:

![R5om3I2r0i](https://github.com/user-attachments/assets/574c385b-f198-4d89-98e4-1b78fe135d23)

I'm not sure if that's by choice. I signed in to Zipline using Authentik on an account that doesn't exist. So it created me a new account. I decided to add a password, and see if I could unlink authentik, and change the account over to just a typical username / password. 

It would not let me unlink the account.

<br />

### Internal Server Error / Avatar Breaking Link

This bug is strange. I've provided animated gifs below to make it easier. It appears that somehow, setting an avatar in Zipline causes authentik / zipline to throw an API error: `"Cant link account, already linked with this provider"`

- Sign into a regular Zipline account, no authentik linked.
- Go to the user settings, and upload a new avatar
- Go down and click the button to link Authentik.
- After seeing the authentik page, you'll then see:
  - `"Cant link account, already linked with this provider"`
- Go back to the Zipline user settings page, and the button will still say "Unlink Authentik", even though it errored out.
  - ![Oc8knSd9RG](https://github.com/user-attachments/assets/11e0fa77-97d8-48b9-8e7b-6b8012080398)
- If you link authentik and sign completely out of Zipline, and try to sign back in using Authentik, you will get the error:
  - `Internal Server Error`

However, if you remove your Zipline avatar completely, and then link your Authentik account, everything works perfect. No errors. I can sign out and sign back in using that Authentik account.

Here are some screenshots.

This gif is of it failing. I have an avatar set, and no account is currently associated to that Authentik account I'm trying to link:
![sjFngTlfdP](https://github.com/user-attachments/assets/1aef45ea-7e33-469d-8107-7bc76f7a9de5)

The odd thing though, is that if I remove my avatar, it works. In this gif, I remove my avatar and then try to link Authentik with my account:

![s6TtkPAwWC](https://github.com/user-attachments/assets/91a28a95-9fcf-4c92-b7db-9a43230de09d)

<br />

- If I remove the avatar, add my Authentik account, and then sign completely out and sign back in using Authentik, it works perfect.
- If I add a new avatar, and then sign out and attempt to sign back in using Authentik, I get a blank page with `Internal Server Error`.

<br />

Here is a gif of me linking Authentik to my Zipline account, with an avatar set, and trying to sign in using Authentik:
![5wML44jl2d](https://github.com/user-attachments/assets/584e5c3c-c5fb-4623-9796-af225b558100)

<br />

And this is a gif of me removing the avatar from my account and then attempting to sign in:
![9kkHZyJ404](https://github.com/user-attachments/assets/44bf1e82-c16d-435e-a22e-123540f842ee)

**Comment by diced** [comment]
> In short, yes, I can now use Authentik.

Glad it works now, and with that change I think any OIDC provider (like authelia, keycloak) should work in place of authentik.

> Appreciate it. There's a few things to note (or if you want a new ticket):

Thank you so much for the detailed bug reports, and yea I think it would be better if you created separate issues for these so its easier to track for me. I think I'll take a look at these issues soon once I fix my authentik setup hopefully.

**Comment by Aetherinox** [comment]
Thanks, I'll create another.

**Comment by alepouna** [comment]
Followed the goauthentik docs and this thread to make sure the offline_access is enabled, but I'm still getting this very same error. Is there any place to further troubleshoot? I can see Zipline passes the offline_access as a scope correctly. v4.4.0.
