### ISSUE TITLE
Bug: Authentik Integration

### ISSUE THREAD

**Issue by Aetherinox** [dicedtomatoreal/typex#603]
### What happened?

Two different behaviors occur at the moment:
- Unable to unlink authentik on a freshly created account
- Setting an avatar on your Zipline account causes authentik to not function properly.

<br />

I am mentioning both in the same ticket because I'm unsure if these are related or different issues. They seem to merge into each other.

<br>

---

<br>

### Unable to unlink authentik on a freshly created account

- Integrate Authentik into your copy of Zipline, but do not link authentik to any accounts.
- On the login page, click the button to sign in using Authentik.
- You should be redirected back to Zipline under a new user.
- Set a password for the account
- Attempt to **unlink** Authentik and you will get the error below:
  - ![R5om3I2r0i](https://github.com/user-attachments/assets/574c385b-f198-4d89-98e4-1b78fe135d23)

<br>

---

<br>

### Avatars break authentik integration

- Sign into a regular Zipline account with username / password, no authentik linked.
- Go to the user settings, and upload a new avatar
- Go down and click the button to link Authentik.
- After going through the authentik process, you'll be redirected to an api page error:
  - `"Cant link account, already linked with this provider"`
- Go back to the Zipline user settings page, and the button will still say "Unlink Authentik", even though it errored out.
  - ![Oc8knSd9RG](https://github.com/user-attachments/assets/11e0fa77-97d8-48b9-8e7b-6b8012080398)
- **Sign-In Symptoms**: 
  - `(With avatar):` If you link authentik and sign completely out of Zipline, and try to sign back in using Authentik, you will get the error:
    - `Internal Server Error`
  - `(Without avatar):` Signing out and back in with Authentik works fine.

Here are some screenshots.

This gif is of it failing. I have an avatar set, and no account is currently associated to that Authentik account I'm trying to link:
![sjFngTlfdP](https://github.com/user-attachments/assets/1aef45ea-7e33-469d-8107-7bc76f7a9de5)

The odd thing though, is that if I remove my avatar, it works. In this gif, I remove my avatar and then try to link Authentik with my account:

![s6TtkPAwWC](https://github.com/user-attachments/assets/91a28a95-9fcf-4c92-b7db-9a43230de09d)

<br>

- If I remove the avatar, add my Authentik account, and then sign completely out and sign back in using Authentik, it works perfect.
- If I add a new avatar, and then sign out and attempt to sign back in using Authentik, I get a blank page with `Internal Server Error`.

<br>

Here is a gif of me linking Authentik to my Zipline account, with an avatar set, and trying to sign in using Authentik:
![5wML44jl2d](https://github.com/user-attachments/assets/584e5c3c-c5fb-4623-9796-af225b558100)

<br>

And this is a gif of me removing the avatar from my account and then attempting to sign in:
![9kkHZyJ404](https://github.com/user-attachments/assets/44bf1e82-c16d-435e-a22e-123540f842ee)

### Version

other (provide version in additional info)

### What browser(s) are you seeing the problem on?

- Firefox (latest)
- Chrome (latest)

### Zipline Logs
Typical logs, no errors:

```shell
tasks::deletefiles] found 0 expired files files=[]
tasks::clearinvites] found 0 expired invites files=[]
tasks::clearinvites] found 0 max used invites files=[]
tasks::maxviews] found 0 expired files files=[]
tasks::maxviews] found 0 expired urls dests=[]
tasks::metrics] created metric id="cm1o3x8yq00xlmvlx6f7a27ea" metric={"files":1,"urls":1,"users":1,"storage":35781,"fileViews":1,"urlViews":0,"filesUsers":[{"username":"Test","sum":1,"storage":35781,"views":1}],"urlsUsers":[{"username":"Test","sum":1,"views":0}],"types":[{"type":"image/png","sum":1}]}
tasks::deletefiles] found 0 expired files files=[]
tasks::maxviews] found 0 expired files files=[]
tasks::clearinvites] found 0 expired invites files=[]
tasks::maxviews] found 0 expired urls dests=[]
tasks::clearinvites] found 0 max used invites files=[]
tasks::metrics] created metric id="cm1o3xts9000mmvlxhacfe3ac" metric={"files":1,"urls":1,"users":1,"storage":35781,"fileViews":1,"urlViews":0,"filesUsers":[{"username":"Test","sum":1,"storage":35781,"views":1}],"urlsUsers":[{"username":"Test","sum":1,"views":0}],"types":[{"type":"image/png","sum":1}]}
```

### Browser Logs
Normal browser dev prints, no errors.

```shell
Ruleset ignored due to bad selector. 0807c480506a71ea.css:11:126856
Expected declaration but found ‘@mixin’.  Skipped to next declaration. 0807c480506a71ea.css:59:3163
Expected declaration but found ‘@mixin’.  Skipped to next declaration. 0807c480506a71ea.css:59:3338
Expected declaration but found ‘@mixin’.  Skipped to next declaration.
```

### Additional Info

Using v4 of Zipline.
Latest version of Authentik.

**Comment by sahara101** [comment]
Hey @Aetherinox sorry to ask here. Can you tell me please which Authentik settings you have used? I am getting the 500 error without any avatar :(

**Comment by Aetherinox** [comment]
It's cool, ask whatever.

You mean in regards to the application / provider / etc?

### Application Tab:
![iCvAlKiTQ8](https://github.com/user-attachments/assets/b304ecdc-58aa-44ca-ba46-30ce49d190fd)


### Provider Tab

When creating the provider, make sure to select **OAuth**:
![image](https://github.com/user-attachments/assets/5b3483fe-7188-4562-89d3-80d69bd9c3c6)

![Pro](https://github.com/user-attachments/assets/b2ef4a49-6e3b-4a08-a825-5aafad0b84d9)


### Outposts
You can skip this since this is an oAuth app.


### Zipline Docker-compose.yml

You need to add the 5 base settings as new env variables:

```yml
            - OAUTH_AUTHENTIK_CLIENT_ID=${ZIPLINE_OAUTH_AUTHENTIK_CLIENT_ID}
            - OAUTH_AUTHENTIK_CLIENT_SECRET=${ZIPLINE_OAUTH_AUTHENTIK_CLIENT_SECRET}
            - OAUTH_AUTHENTIK_AUTHORIZE_URL=${ZIPLINE_OAUTH_AUTHENTIK_AUTHORIZE_URL}
            - OAUTH_AUTHENTIK_USERINFO_URL=${ZIPLINE_OAUTH_AUTHENTIK_USERINFO_URL}
            - OAUTH_AUTHENTIK_TOKEN_URL=${ZIPLINE_OAUTH_AUTHENTIK_TOKEN_URL}
```

Then in my `.env` file, I have:
```
ZIPLINE_OAUTH_AUTHENTIK_CLIENT_ID=XX
ZIPLINE_OAUTH_AUTHENTIK_CLIENT_SECRET=XX
ZIPLINE_OAUTH_AUTHENTIK_AUTHORIZE_URL=https://auth.domain.com/application/o/authorize/
ZIPLINE_OAUTH_AUTHENTIK_USERINFO_URL=https://auth.domain.com/application/o/userinfo/
ZIPLINE_OAUTH_AUTHENTIK_TOKEN_URL=https://auth.domain.com/application/o/token/
```

The `ZIPLINE_OAUTH_AUTHENTIK_CLIENT_ID` and `ZIPLINE_OAUTH_AUTHENTIK_CLIENT_SECRET` are given to you when you create the **Provider** within Authentik.

**Comment by sahara101** [comment]
Hmm I have them and still get 500. No idea what is wrong.

**Comment by Aetherinox** [comment]
May be something the dev has to mess with. When I added Authentik, I didn't do anything special. I had Authentik pre-set up prior to today's patch, so I just updated and clicked the button.

You getting any type of error? In the zipline container, authentik logs, etc. Sometimes 500s can be a owner / group / permission issue.

**Comment by sahara101** [comment]
Unfortunately no. Authentik log says login success, other than this I only see the 500 error. 
Maybe I will try from the beginning

**Comment by Aetherinox** [comment]
Htm.. I'm looking through my config to see if I did anything extra.

You can try changing the authentication flow from explicit to implicit, just for giggles.

Other thing I can think of is ensuring it has the proper URL in the authentik redirect. I remember when I did it yesterday, it was showing `http` instead of `https`, I also have `CORE_RETURN_HTTPS` set to `true`.

Only other thing to note is that I use Traefik, and I have a middleware to secure the headers which runs before the site loads.

**Comment by sahara101** [comment]
So I added CORE_RETURN_HTTPS, and manually changed the redirect to https. Seems it does not like that:

The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri).

I am also using traefik 

CUSTOM REQUEST HEADERS
X-Forwarded-Proto: https
CUSTOM RESPONSE HEADERS
X-Forwarded-Proto: https
X-Robots-Tag: none,noarchive,nosnippet,notranslate,noimageindex
server:
HOSTS PROXY HEADERS
X-Forwarded-Host
SSL PROXY HEADERS
https
STS SECONDS
63072000
STS INCLUDE SUBDOMAINS
True
STS PRELOAD
True
FORCE STS HEADER
True
CONTENT TYPE NOSNIFF
True
BROWSER XSS FILTER
True
REFERRER POLICY
strict-origin-when-cross-origin

Changing auth flow also does not work :(

**Comment by diced** [comment]
Seems like these issues were caused by some oversights after implementing sessions. After fixing sessions, it seems to be working perfectly fine!

Another note: I have renamed everything from authentik to oidc, so env vars like `OAUTH_AUTHENTIK_X` are now `OAUTH_OIDC_X`.

https://github.com/diced/zipline/commit/67a7d44198c306e935f2a74c0ef7ecd552b15a8d

**Comment by Aetherinox** [comment]
So this one is a bit weird:

This gif is about 31 seconds in duration. I haven't even typed in my credentials yet and I noticed the button glitches out:
![P5ExNbbxOS](https://github.com/user-attachments/assets/71f49510-72aa-486c-8eb3-69d2e18327f0)

Every time the button blinks in the browser, I see the following in dev console:
```
XHRGET
https://share.domain.com/api/user
[HTTP/3 401  155ms]

XHRGET
https://share.domain.com/api/user
[HTTP/3 401  61ms]

XHRGET
https://share.domain.com/api/user
[HTTP/3 401  63ms]

```
When I actually click the login button, I get a 500:
```
{"statusCode":500,"code":"P2022","error":"Internal Server Error","message":"\nInvalid `prisma.user.findUnique()` invocation:\n\n\nThe column `User.sessions` does not exist in the current database."}
```

Returning to the old version and things work again.

Tried the OCID button, and I get:
![P0tA2lEWj4](https://github.com/user-attachments/assets/ce42a6fd-54cd-4d60-bce8-66274dfca291)

No changes made.

Going to test more

<br />

---

<br />

**Edit**: Yeah, once I revert to the previous version, Authentik integration works. Minus the whole avatar issue.
I also made sure to change the env vars from `AUTHENTIK_` to `OCID_`

![CvKU79eRAe](https://github.com/user-attachments/assets/1164b4de-b029-40c0-9a10-5c3dc05f1e1c)

**Comment by diced** [comment]
> This gif is about 31 seconds in duration. I haven't even typed in my credentials yet and I noticed the button glitches out:

This is intended behavior (though i dont know why its doing it that frequent..), it just refetches every once in a while to check if you are logged in, and if you are it auto redirects to /dashboard.

> When I actually click the login button, I get a 500:

This is because I made some changes to the database schema, so you have to run `pnpm db:prototype` (similar to how you first ran v4, just do the same steps!). sorry for not including this in my comment :)

> Tried the OCID button, and I get:

You have to go into authentik, and edit provider, then look at the redirect uris and change the one that has `https://domain.com/api/oauth/authentik` to have `oidc` instead of `authentik` at the end.

> I also made sure to change the env vars from AUTHENTIK_ to OCID_

In the screenshot you have `OIDC` but you typed `OCID`, so make sure all your variables are spelled correctly (trust me i messed this up too, idk why oidc is hard to type lol)

anyway, I think that covered everything here, lmk if you have any issues with syncing the db - if you have discord feel free to join too if im not available here

**Comment by Aetherinox** [comment]
Appreciate the info. I'll go through and do all these steps.

> https://domain.com/api/oauth/authentik to have oidc instead of authentik at the end.

I feel dumb for that one, should have thought about it earlier today. Brain is overloaded.

Thanks again.

**Comment by Aetherinox** [comment]
One more thing to note, I found time to try this out. When pnpm db is ran, I get

```
✔ Do you want to ignore the warning(s)? … yes
Error: ERROR: invalid input value for enum "OAuthProviderType_new": "AUTHENTIK"
   0: sql_schema_connector::apply_migration::migration_step
           with step=AlterEnum(AlterEnum { id: MigrationPair { previous: EnumId(1), next: EnumId(2) }, created_variants: ["OIDC"], dropped_variants: ["AUTHENTIK"], previous_usages_as_default: [] })
             at schema-engine/connectors/sql-schema-connector/src/apply_migration.rs:21
   1: sql_schema_connector::apply_migration::apply_migration
             at schema-engine/connectors/sql-schema-connector/src/apply_migration.rs:10
   2: schema_core::state::SchemaPush
             at schema-engine/core/src/state.rs:436

 ELIFECYCLE  Command failed with exit code 1.
```

When I sign in using OIDC, I get an internal server error, and the authentik links have been changed. And the normal "Login" button does nothing at all. Maybe because of the error.

Combination of errors

```
XHRGET
https://share.domain.com/api/user
[HTTP/3 401  76ms]

XHRGET
https://share.domain.com/api/user
[HTTP/3 401  72ms]

XHRGET
https://share.domain.com/api/user
[HTTP/3 401  63ms]

XHRPOST
https://share.domain.com/api/auth/login
[HTTP/3 500  65ms]

XHRPOST
https://share.domain.com/api/auth/login
[HTTP/3 500  68ms]

XHRGET
https://share.domain.com/api/user
[HTTP/3 401  67ms]

XHRGET
https://share.domain.com/api/user
[HTTP/3 401  64ms]
```

```
statusCode 
code | "P2022"
error | "Internal Server Error"
message | "\nInvalid `prisma.user.findUnique()` invocation:\n\n\nThe column `User.sessions` does not exist in the current database."
```

The weird thing with the normal login button though, if you stop clicking it, wait like 20-30 seconds, and then click it, it actually brings up the OIDC and tries to prompt you for a passkey.  So it's like playing the role of both buttons. All I was trying to do is sign in using my normal username / password since the OIDC button wouldn't work.

**Comment by Aetherinox** [comment]
Just an update.

I decided once I got free time, I'd just wipe the database, and start a fresh install. After I did a fresh install and tried Authentik again, it worked. I also noticed that the login button stopped doing that periodic flashing thing. So it may just have been a db migration issue.

Signing in with avatar also works.

Appreciate the fixes. Hopefully that's the last of the issues.

---

Installing the beta is a two part task (and I'm putting this here in case anyone else needs help).

Once the container is started, you have to run the following on the PostgreSQL database:

```postgresql
DO
$$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.tablename) || ' CASCADE';
    END LOOP;
END
$$;
```

Afterwards, then run
```
pnpm db:prototype
```

Then it should start up fine.

**Comment by diced** [comment]
> I'd just wipe the database, and start a fresh install

yea unfortunately this is usually the best way to fix database issues while v4 is in development, since I don't tag releases on github I'm unable to provide how to update without needing to do so, but I do do this in the discord server if you are able to join. it's basically where anything v4 related is talked about, bugs are just reported here for my sake so I don't forget about them.

hopefully there aren't much db changes anymore since we're nearing the final stages of v4

**Comment by Aetherinox** [comment]
Sounds good. Yeah I'm not using v4 as a perm solution yet until it releases. I don't want to start uploading a bunch of images, and then I need to wipe the DB, so for now I'm just testing it.

But v4 definitely looks good. I've liked it so far. 

I'm actually in the discord. That's how I found the database query above. It was posted by another user in the discord.
