### ISSUE TITLE
Bug: inconsistent copy url when custom domain is specified

### ISSUE THREAD

**Issue by teslazap** [dicedtomatoreal/typex#604]
### What happened?

A user specified a custom domain in the Manage Account section.
After the file is uploaded Zipline presents the correct domain to the user and it can be copied immediately.
If the user go back to Files and click on copy the url again, the default GUI domain is being copied rather than the custom one.

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox, Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment]
This is by design, domains and full urls are not supposed to be tied to any file. Alternatively I think I might be open to a feature in which on the dashboard you can "save a domain" and all links copied will use that saved domain instead of the domain used to access the dashboard.
