### ISSUE TITLE
When using CURL command is it possible to designate the folder?

### ISSUE THREAD

**Issue by mptpro** [dicedtomatoreal/typex#611]
### What happened?

I've tried this, but I don't think the syntax is correct:

`curl -H "Content-Type: multipart/form-data" -H "authorization: MZfakecode" -F file=@$FILE https://example.com/api/upload |  x-zipline-folder 10 `

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

**Comment by TacticalTechJay** [comment]
It isn't... it's another header, use the `-H` argument again for x zipline folder

**Comment by mptpro** [comment]
Thank you!  That worked.
