### ISSUE TITLE
Bug: UPLOADER_DEFAULT_EXPIRATION is not reflected in upload UI

### ISSUE THREAD

**Issue by matejdro** [dicedtomatoreal/typex#624]
### What happened?

Steps to reproduce:

1. Set `UPLOADER_DEFAULT_EXPIRATION` to some value, let's say `30d`
2. Open Upload files page
3. Select Options

BUG: Default option appears to falsely be "Never". By not touching this option and just upload, files will have proper expire date, so it appears only the UI is the issue.

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox

**Comment by diced** [comment]
The one you set in the upload options modal is supposed to override the default, but I do think it's a good idea to have the default setting somewhere within there so users know. I'll add it to the v4 roadmap.

**Comment by matejdro** [comment]
> The one you set in the upload options modal is supposed to override the default

If that was the case then uploaded default expiration would not work at all. Since options modal defaults to Never, it would always override it to Never
