### ISSUE TITLE
Bug: copy link button doesnt work

### ISSUE THREAD

**Issue by sobakintech** [dicedtomatoreal/typex#625]
### What happened?

The copy link button in URLs tab doesnt work

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

**Comment by diced** [comment]
the copy url buttons won't work when accessing the dashboard through http sometimes, you might be able to see more info in the developer tools console.

**Comment by diced** [comment]
Going to close this, in v4 a lot of the places that have a "copy button" have alternative links that you can manually right click > copy link via the browser.
