### ISSUE TITLE
Bug: Keep original name is not working

### ISSUE THREAD

**Issue by matejdro** [dicedtomatoreal/typex#631]
### What happened?

When uploading a file with a specific name:

![image](https://github.com/user-attachments/assets/35a0293f-6ec9-42ec-90f4-333a5594d764)

The name of that file will not be kept:

![image](https://github.com/user-attachments/assets/dacdf1a2-8432-44f3-8f85-aeb118df1f83)

### Version

3.7.10 

### What browser(s) are you seeing the problem on?

Firefox

### Zipline Logs

```shell
2024-11-20 08:25:13,335 AM debug [upload] recieved upload (len=1) [{"fieldname":"file","originalname":"my-image.jpg","mimetype":"image/jpeg","size":57576,"encoding":"7bit"}]
2024-11-20 08:25:13,344 AM info  [upload] User administrator (1) uploaded hDcaPATl4i9ybBn.jpg (39)
```

### Additional Info

Option is enabled:

![image](https://github.com/user-attachments/assets/fa0482ef-e897-4c7a-9b8d-0592a1c91859)

My config:

```
UPLOADER_ADMIN_LIMIT=500gb
UPLOADER_DEFAULT_FORMAT=random
UPLOADER_LENGTH=15
UPLOADER_DEFAULT_EXPIRATION=30d
```

the rest is default

**Comment by Stef-00012** [comment]
that's the correct behaviour, you set the format as `random`, so it uses a random mix of characters for it

try to set the format to `name`

**Comment by matejdro** [comment]
But I want the URL to be random. I just want the name of the file displayed in the UI to be original name.

Option clearly states: `This will not change the name format in the URL.`. So it should be separate, right?

**Comment by TacticalTechJay** [comment]
Hmmm

**Comment by TacticalTechJay** [comment]
The title of the file when viewed could to be changed to show the original name, but it'd mean opening a pull request x3.
Its primary purpose is when downloading it. There, it'll show the original file name in the save window.

**Comment by matejdro** [comment]
Ah, then I have misunderstood the option. Can we turn that into a feature request then? :)

**Comment by Stef-00012** [comment]
> Ah, then I have misunderstood the option. Can we turn that into a feature request then? :)

you can try in https://github.com/diced/zipline/discussions/433
maybe check if someone else already did

**Comment by matejdro** [comment]
Thanks, did it.

**Comment by matejdro** [comment]
Would you be open for a PR for this?

**Comment by diced** [comment]
> Would you be open for a PR for this?

not in v3, but I'm open to adding this into v4
