### ISSUE TITLE
Bug: cURL upload set videos mimetype as application/octet-stream

### ISSUE THREAD

**Issue by psoldunov** [dicedtomatoreal/typex#632]
### What happened?

When trying to upload an MP4 video file with cURL command, video uploads as "application/octet-stream" instead of "video/mp4" and is not visible in "Files" panel unless "Show non-media files" is toggled on.

The command I use:
```sh
curl -H "Content-Type: multipart/form-data" -H "authorization: $ZIPLINE_TOKEN" -F file=@$VIDEO_PATH $ZIPLINE_UPLOAD_URL
```

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

**Comment by diced** [comment]
you can try the `UPLOADER_ASSUME_MIMETYPES=true` variable (sorry this isn't documented rn), which will use the filename extension (in your case it might be video.mp4) and map it to a common mimetype like `video/mp4`

**Comment by psoldunov** [comment]
> you can try the `UPLOADER_ASSUME_MIMETYPES=true` variable (sorry this isn't documented rn), which will use the filename extension (in your case it might be video.mp4) and map it to a common mimetype like `video/mp4`

Thank you for the response, variable did work however videos don't play back when uploaded with curl despite showing correct mimetype. If same video is uploaded through webgui - no problem at all.

[Uploaded with cURL](https://zipline.theswisscheese.com/u/RVyVKF.mp4)
[same file uploaded with webgui](https://zipline.theswisscheese.com/u/YQsF2w.mp4)

**Comment by diced** [comment]
Gave it a try myself, and I wasn't able to reproduce it. I tried downloading the video from the "uploaded with curl" link and opened with mpv:
```
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: moov atom not found
[lavf] avformat_open_input() failed
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: moov atom not found
[lavf] avformat_open_input() failed
Failed to recognize file format.
```

the problem is probably with the file instead?

heres the video I uploaded via curl, and it loads in the browser, and dashboard (not shown in the screenshot)
![image](https://github.com/user-attachments/assets/af942ae2-3a4e-45c7-8a2f-9dd04473d38a)

**Comment by psoldunov** [comment]
Yes indeed, the issue is probably somewhere in my wf-recorder upload script. Tried curl straight from the terminal and it works as expected. Thank you for looking into it!
