### ISSUE TITLE
Bug: authelia "The state is missing or does not have enough characters"

### ISSUE THREAD

**Issue by trexxeon** [dicedtomatoreal/typex#633]
### What happened?

Using authelia as oidc provider in v4 gives:

Authorization Request failed with error: The state is missing or does not have enough characters and is therefore considered too weak. Request parameter 'state' must be at least be 8 characters long to ensure sufficient entropy.

### Version

other (provide version in additional info)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Zipline Logs

```shell
nothing particular
```

**Comment by diced** [comment]
thanks for the bug report! should be fixed in da875e451cdad38b46ca048e1d963dcec4fc3e78, I wasn't able to test it since setting up authelia locally is a bit of a chore, but the secret Zipline generates is around 60 characters now so this error shouldn't show up.
