### ISSUE TITLE
Bug: Handling large text files is difficult

### ISSUE THREAD

**Issue by matejdro** [dicedtomatoreal/typex#634]
### What happened?

It seems like zipline has trouble with handling long text files.

Steps to reproduces:

1. Upload a big txt file (>10MB)
2. Attempt to download this file

At least on Firefox, when opening file info page, whole page fill freeze while attempting to render a preview for this huge file, making it difficult to click on the download link.

Additionally, even "raw link" is not the raw txt file, it opens it in some kind of preview, wrapped in bunch of HTML which also makes just wgetting the file very difficult. Even `?download=true` seems to have no effect.

A possible solution:

1. Limit maximum preview lengths (maybe only show a couple hunded KB of the text file at most in the preview?).
2. Provide a way to get the raw txt link, without redirecting to the `/code`. Maybe `?raw=true` flag?

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox

**Comment by diced** [comment]
> Provide a way to get the raw txt link, without redirecting to the /code. Maybe ?raw=true flag?

You can go to `/r/{the name}.txt` to get the raw link

> Limit maximum preview lengths (maybe only show a couple hunded KB of the text file at most in the preview?).

I will add this into v4, never thought about this as an issue 😂

**Comment by matejdro** [comment]
Ah thank you `/r/` works. Thanks!

 Do you want to keep this issue open for v4 or do I copy paste suggestion to the v4 thread?

**Comment by diced** [comment]
you can close it if you want to-i've already added this to the roadmap so it'll get fixed sometime. or even better i can just add the v4 tag to this issue and treat it as a v4 bug instead which I will do.

**Comment by matejdro** [comment]
Okay, let's do that then. Thanks a lot!

**Comment by diced** [comment]
Fixed in a13cb8220131bf65de8af73044d8cedd97919af8, anyone finding this issue on v3 should know that the issue still exists in v3 but once v4 comes out that's no longer a problem.

**Comment by matejdro** [comment]
Thank you!
