### ISSUE TITLE
Images section hangs when there are many images

### ISSUE THREAD

**Issue by Excigma** [dicedtomatoreal/typex#7]
When you have over 1 thousand screenshots, the image section of the dashboard hangs while your browser tries to download over 75mb with of image data, taking a total of over 55 seconds to fully load the page.

Potential fixes: 
- Pagination
- Lazy loading

**Comment by dicedtomatoreal** [comment]
This is a known issue fix coming out soon

**Comment by dicedtomatoreal** [comment]
Fixed in latest commit!!!!!!!!!!!!!!!!!!
